clc-pr-2017-12-16
kubernetes/kubernetes-docs-zh pull request #107
Opened 2017-12-16 06:17 UTC by zhangqx2010

2017-12-16 06:51 UTC, xiaosuiba requested changes
先看了一半，建议针对 trans 工具的结果进行仔细修改。

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +title: 在 CenturyLink Cloud 上运行 Kubernetes
CenturyLink Cloud 保留原文或翻译为 CenturyLink 云，全文是否需要保持一致？

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +您可以使用单个命令完成所有这些任务。我们已经使 Ansible 的手册执行这些任务，参考 [这里](https://github.com/CenturyLinkCloud/adm-kubernetes-on-clc/blob/master/ansible/README.md)。
我们已经可以使用 Ansible playbooks 执行这些任务，请参考[这里]

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +如果遇到任何问题或需要任何帮助，我们都会帮助您。通过以下任何方式联系我们：
请通过/您可以通过

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +- 提交一个github问题
github 前后空格

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +## 虚拟机或物理服务器的群集，随您选择。
您可以任意选择虚拟机或物理服务器组成集群。

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +- 我们在虚拟机或物理服务器上支持 Kubernetes集 群。如果工作节点（minion）使用物理服务器，请使用 --minion_type=bareMetal 标志。
无论虚拟机还是物理服务器均支持 Kubernetes 集群。

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +4) 使用网络内的虚拟机或 [配置与 CenturyLink Cloud 网络的 VPN 连接。](https://www.ctl.io/knowledge-base/network/how-to-configure-client-vpn/)
使用网络内的虚拟机或通过配置连接到 CenturyLink Cloud 网络的 VPN 来从您的机器访问 CenturyLink Cloud 网络。

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +如果您使用的是 Ubuntu 14，为了您的方便，我们已经提供了一个指导安装要求并安装脚本。
方便起见，我们已经提供了一个安装依赖和脚本的分步指导。

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +大约需要15分钟来创建群集。一旦脚本完成，它会输出一些命令来帮助你在你的机器上设置 kubectl 指向新的群集。
它会输出一些命令来帮助您在机器上设置 kubectl 以指向新的集群

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +集群创建完成后，会保存其配置文件本地在您的管理主机上，在以下目录中
会将其配置文件本地保存在您管理主机的以下目录中：

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +#### 群集创建：脚本选项
集群创建：脚本选项

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +此脚本必须从创建群集的同一台主机（或者具有存储群集工件文件 ```~/.clc_kube/$cluster_name``` 的主机）运行。
群集 -> 集群
或者在 ```~/.clc_kube/$cluster_name``` 路径保存了集群 artifact 文件的主机

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +#### 群集扩展：脚本选项
群集 -> 集群 
请全文替换

2017-12-16 06:51 UTC, xiaosuiba commented on docs/getting-started-guides/clc.md
> +1) 使用我们的Python脚本：
Python 空格

2017-12-23 13:51 UTC, zhangqx2010 commented
Thanks for review!

2017-12-24 07:12 UTC, merged