tasks-core-metrics-pipeline-2017-12-17
kubernetes/kubernetes-docs-zh pull request #109
Opened 2017-12-17 08:08 UTC by pigletfly

core-metrics-pipeline translation

2017-12-21 01:21 UTC, xiaosuiba requested changes
请参考。
PS：trans 工具生成的文本由于换行等影响，可能导致不连续的翻译，建议仔细检查。

2017-12-21 01:21 UTC, xiaosuiba commented on docs/tasks/debug-application-cluster/core-metrics-pipeline.md
> +例如通过使用 `kubectl top` 命令，或由群集中的控制器使用，例如，Horizontal Pod Autoscale 可以使用这些指标作出决策。
这里建议处理下，用括号翻译法：
这些指标可以直接被用户访问（例如xxx），或由集群中的控制器使用（例如xxx）
群集 -> 集群，请全文检索下，trans 的默认翻译为群集

2017-12-21 01:21 UTC, xiaosuiba commented on docs/tasks/debug-application-cluster/core-metrics-pipeline.md
> +通过 Metrics API，您可以获取指定 node 或 pod 当前使用的资源量。这个 API 不存储指标值，所以例如要获取某个指定 node 10 分钟前的资源使用量是不可能的。
例如要获取 -> 可以去掉要字

2017-12-21 01:21 UTC, xiaosuiba commented on docs/tasks/debug-application-cluster/core-metrics-pipeline.md
> +[指标服务器](https://github.com/kubernetes-incubator/metrics-server) 是集群范围资源使用数据的聚合器。
这里的 Server 应该指软件服务，是否考虑保留原文（如您前文的 Metrics API），或翻译为 指标服务 （类比 API Server）

2017-12-21 01:21 UTC, xiaosuiba commented on docs/tasks/debug-application-cluster/core-metrics-pipeline.md
> +它在 Kubernetes 1.7+ 中支持（请参阅下面的详细信息）。
您可以使用 Kubernetes 1.7+ 中引入的 [deployment yamls](https://github.com/kubernetes-incubator/metrics-server/tree/master/deploy) 文件来部署。

2017-12-21 01:21 UTC, xiaosuiba commented on docs/tasks/debug-application-cluster/core-metrics-pipeline.md
> +指标服务器从每个节点上的 [Kubelet](/docs/admin/kubelet/) 暴露的 Summary API 中采集指标信息。
暴露的 -> 公开的

2017-12-23 10:26 UTC, pigletfly commented
updated

2017-12-24 07:16 UTC, markthink reviewed
中英文段落间隔太大，建议把间隔调整短一些，方便其他人review。

2017-12-24 09:56 UTC, merged