home-index-2017-12-03
kubernetes/kubernetes-docs-zh pull request #114
Opened 2017-12-18 09:20 UTC by tianshapjq

2017-12-18 10:22 UTC, pigletfly requested changes

2017-12-18 10:22 UTC, pigletfly commented on docs/home/index.md
> +## 概念，任务和教程
这里用中文的 、 ？

2017-12-18 10:33 UTC, lichuqiang commented on docs/home/index.md
> +* [Concepts](/docs/concepts/) 提供了对 Kubernetes 如何工作的深入理解。
Concepts、Tasks以及后面的Reference等相关目录名称的表述是否翻译，全文应保持一致

2017-12-18 10:33 UTC, lichuqiang commented on docs/home/index.md
> +Kubernetes 文档可以帮助您设置 Kubernetes，了解系统，或者让您的应用程序和工作负载在 Kubernetes 上运行。如果想要了解 Kubernetes 是什么和它是如何运行的，请参阅 "[What is Kubernetes](/docs/concepts/overview/what-is-kubernetes/)"。
“如果想要了解 Kubernetes 是什么和它是如何运行的”需要断句。

2017-12-18 10:33 UTC, lichuqiang commented on docs/home/index.md
> +[工具](/docs/tools/) 页面包含 Kubernetes 的本地和第三方工具列表。
native 这里指原生的

2017-12-18 10:33 UTC, lichuqiang commented on docs/home/index.md
> +master 组件、node 组件和 kubectl 客户端之间允许有一定的版本偏差。Node 可能落后 master 两个小版本，但是不能超过 master 小版本。客户端可能落后也可能超过 master 一个小版本。
“但是不能超过 master 小版本” 这样表述有点别扭，“不能超过 master 版本”就可以，没有歧义

2017-12-20 01:08 UTC, tianshapjq commented
@pigletfly @lichuqiang fixed~

2017-12-20 01:13 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +Kubernetes 文档可以帮助您设置 Kubernetes，了解系统，或者让您的应用程序和工作负载在 Kubernetes 上运行。如果想要了解 Kubernetes 是什么，和它是如何运行的，请参阅 "[What is Kubernetes](/docs/concepts/overview/what-is-kubernetes/)"。
[What is Kubernetes] 顺带翻译一下

2017-12-20 01:14 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +[Kubernetes 基本概念的互动教程](/docs/tutorials/kubernetes-basics/) 通过一个虚拟的终端让您能够在网页浏览器中尝试 Kubernetes。您能够在几分钟内了解 Kubernetes 系统和如何部署、暴露、伸缩和升级一个容器化的应用。
这里的 ‘’和‘’ 不如 “以及”好

2017-12-20 01:19 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +master 组件、node 组件和 kubectl 客户端之间允许有一定的版本偏差。Node 可能落后 master 两个小版本，但是不能超过 master 版本。客户端可能落后也可能超过 master 一个小版本。
翻译有误：根据下文，这里不是落后小版本，是一个大版本！

2017-12-20 01:21 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +补丁版本通常包含对关键错误的修复。您应该运行给定小版本的最新补丁版本。
最后一句拗口。直接写出：您应该运行当前使用版本的最新小版本。

2017-12-20 01:27 UTC, tianshapjq commented on docs/home/index.md
> +master 组件、node 组件和 kubectl 客户端之间允许有一定的版本偏差。Node 可能落后 master 两个小版本，但是不能超过 master 版本。客户端可能落后也可能超过 master 一个小版本。
不会啊，v1.8中的8就是小版本号，一般情况下完整的版本号应该是类似于v1.8.1这种，第一个1是大版本，8是小版本，最后的1是补丁版本。所以翻译应该没错啊。

2017-12-20 01:32 UTC, tianshapjq commented on docs/home/index.md
> +补丁版本通常包含对关键错误的修复。您应该运行给定小版本的最新补丁版本。
@zhangxiaoyu-zidif 这里如果翻译成最新小版本的话，会不会造成这样的误解：当前是v1.8.1，最新的是v1.8.2，如果是小版本的话同样都是v1.8，已经是最新了，那就不用升级了。原文意思应该是在小版本不变的情况下，尽量升级最新的补丁版本。

2017-12-20 01:49 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +补丁版本通常包含对关键错误的修复。您应该运行给定小版本的最新补丁版本。
嗯，有道理。

2017-12-20 01:51 UTC, zhangxiaoyu-zidif commented on docs/home/index.md
> +master 组件、node 组件和 kubectl 客户端之间允许有一定的版本偏差。Node 可能落后 master 两个小版本，但是不能超过 master 版本。客户端可能落后也可能超过 master 一个小版本。
sorry ，I misunderstand that concepts. your translation is correct！

2017-12-20 01:51 UTC, merged

2017-12-20 03:21 UTC, lichuqiang commented
@zhangxiaoyu-zidif 为了保证commit记录清晰，merge 前最好提醒作者rebase一下 :)

2017-12-20 03:48 UTC, zhangxiaoyu-zidif commented
@lichuqiang 这个PR有冲突吗？我合入的时候没有CI警告。我错过了什么吗
Is  there any conflict with this PR. I did not notice any warning. did I miss something?

2017-12-20 04:26 UTC, lichuqiang commented
@zhangxiaoyu-zidif 没有冲突，只是建议review过程中修改产生的一些中间commit记录，在merge之前最好提醒译者squash掉

2017-12-20 04:46 UTC, zhangxiaoyu-zidif commented
OK, got it!