getting-started-guides-mesos-pr-2017-12-19
kubernetes/kubernetes-docs-zh pull request #117
Opened 2017-12-19 04:00 UTC by jiaj12

ready for review

2017-12-20 00:57 UTC, okzhchy requested changes

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
> +看看 Kubernetes on Mesos' 架构 [contrib directory][13].
去掉‘

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
>  ## Support Level
这段没翻译

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
> +我们提供了一个replication controller模板，用来启动上述pod ，可以通过这个链接进行下载 [cluster/addons/dns/kubedns-controller.yaml.in][12] i. 接下来我们来创建可用的 replication controller yaml 文件:
多了i.

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
> +{% assign dns_replicas = "{{ pillar['dns_replicas'] }}" %}
这两段多余的

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
> +{% assign dns_server = "{{ pillar['dns_server'] }}" %}
多余的

2017-12-20 00:57 UTC, okzhchy commented on docs/getting-started-guides/mesos/index.md
>  Log into the future Kubernetes *master node* over SSH, replacing the placeholder below with the correct IP address.
多余的

2017-12-21 07:47 UTC, tianshapjq reviewed
先review了一部分，建议先看看其他人的翻译，按照翻译的规范来，目前的格式存在很大问题

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +Mesos支持Kubernetes与其他一级框架如 [HDFS][1], [Spark][2], 和 [Chronos][3] 的动态资源共享。
按照规范，英文单词的两侧要留有一个空格。全文都得修改。

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +<!--Mesos allows dynamic sharing of cluster resources between Kubernetes and other first-class Mesos frameworks such as [HDFS][1], [Spark][2], and [Chronos][3].
<!-- 和 -->的注释要在单独一行，不要和原文在同一行

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +Mesos支持Kubernetes与其他一级框架如 [HDFS][1], [Spark][2], 和 [Chronos][3] 的动态资源共享。
应该是 Mesos 支持 Kubernetes 和其它 Mesos 一级框架（如 [HDFS]、[Spark] 和 [Chronos]）之间的集群资源动态共享。

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +Mesos集群可以部署在几乎所有IaaS云供应商的基础设施上或你自己的物理数据中心中。Kubernetes on Mesos可以让你可以更容易地把Kubernetes的工作负载从其中一个环境迁移至其他环境中。
你 -> 您
全文都要这么修改

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +本教程将带你安装Mesos集群上的Kubernetes。它提供了如何一步一步地添加Kubernetes到Mesos集群并启动你的第一个nginx web服务器pod。
安装Mesos集群上的Kubernetes -> 在 Mesos 集群上安装 Kubernete
第二句不完整，应该是“提供了***的步骤”

2017-12-21 07:47 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +本教程将带你安装Mesos集群上的Kubernetes。它提供了如何一步一步地添加Kubernetes到Mesos集群并启动你的第一个nginx web服务器pod。
另外，不要一次翻译一大段，分成小段来翻译，不然review的时候不好核对

2017-12-21 08:33 UTC, jiaj12 commented on docs/getting-started-guides/mesos/index.md
> +Mesos集群可以部署在几乎所有IaaS云供应商的基础设施上或你自己的物理数据中心中。Kubernetes on Mesos可以让你可以更容易地把Kubernetes的工作负载从其中一个环境迁移至其他环境中。
我觉得写您很生硬，不过以后我会在翻译中避免使用你或您

2017-12-21 08:36 UTC, tianshapjq commented on docs/getting-started-guides/mesos/index.md
> +Mesos集群可以部署在几乎所有IaaS云供应商的基础设施上或你自己的物理数据中心中。Kubernetes on Mesos可以让你可以更容易地把Kubernetes的工作负载从其中一个环境迁移至其他环境中。
这个是之前确定的规范来着

2017-12-24 07:19 UTC, markthink reviewed
建议格式调整一下，中英间隔不要太大。

2017-12-24 09:52 UTC, merged