reference-setup-tools-kubeadm-kubeadm-alpha-pr-2018-01-02
kubernetes/kubernetes-docs-zh pull request #165
Opened 2018-01-09 06:53 UTC by lichuqiang

2018-01-10 01:50 UTC, pigletfly requested changes

2018-01-10 01:50 UTC, pigletfly commented on docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
> +这种模块化设计使得您能够调用启动过程中原子性的子步骤。 您可以让 kubeadm 完成某些部分，并自己填充您需要自定义的部分。
这里的 boostrap 貌似是  typo，是不是翻译为初始化过程

2018-01-11 08:47 UTC, lichuqiang commented
@pigletfly updated, thanks

2018-01-12 02:22 UTC, tianshapjq commented on docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
>  You can execute preflight checks both for the master node, like in `kubeadm init`, or for the worker node
这里的 preflight checks 应该不是指 preflight 命令，而是指一些前期的检查。如果是命令会用 `` 进行标识的。

2018-01-12 02:22 UTC, tianshapjq commented on docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
> +使用以下操作来完全地配置 bootstrap token。
完全 -> 充分

2018-01-12 02:31 UTC, lichuqiang commented on docs/reference/setup-tools/kubeadm/kubeadm-alpha.md
>  You can execute preflight checks both for the master node, like in `kubeadm init`, or for the worker node
这里很明确就是指 preflight 命令，参考章节标题，包括后面的 `kubeadm alpha phase XXX`都是指相应命令

2018-01-13 09:15 UTC, lichuqiang commented
done ~

2018-01-14 01:07 UTC, merged