tasks-downward-api-volume-expose-pod-information-2018-01-22
kubernetes/kubernetes-docs-zh pull request #190
Opened 2018-01-22 00:51 UTC by pigletfly

2018-01-22 08:05 UTC, lichuqiang requested changes

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +在下一个练习中，您将存储 Container 字段。这是有一个 Container 的 Pod 的配置文件：
"这是有一个..."有点生硬 -> ”这里是包含一个...“

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +在这个配置文件中，您可以看到这个 Pod 有一个 `downwardAPI` 卷，Container 把卷挂载在 `/etc` 。
Container 需要翻译

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +第一个元素指定了名字为 `client-container` Container 的 `limits.cpu` 字段应该存储在名为 `cpu_limit` 的文件中。
Container 需要翻译；
value 需要翻译

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +您可以使用相似的命令入查看 `cpu_request`、`mem_limit` 和 `mem_request` 文件。
”入“ 多余

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
>  ## Capabilities of the Downward API
Capabilities 最好译为”能力“，以和”function“区分
另外从下面的表述来看，描述的也是该特性可以支持哪些字段，即能力范围

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +* 容器的 memory limit
memory 需要翻译，另外 request/limit 是否翻译，可以放到词条issue讨论一下，个人习惯翻译

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +对于容器来说，有时可以获得关于它自己的信息非常有用，而不和 Kubernetes 过度耦合。Downward API 允许容器获取有关自己或集群的信息，而不使用 Kubernetes 客户端
语序需要调整，”without being overly coupled to Kubernetes“是定语，需要放到”非常有用“这部分之前

2018-01-22 08:05 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +一个例子是有一个存在的应用程序，假定它有个特定的环境环境变量有唯一的标识符。一种可能性是包装应用程序，
”An example is an existing application that assumes a particular well-known
  environment variable holds a unique identifier“这句翻译可以再斟酌一下，不是很通顺，”well-known“没有翻译，”环境“重复

2018-01-25 10:33 UTC, pigletfly commented
updated

2018-01-26 09:36 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +在这个配置文件中，您可以看到这个 Pod 有一个 `downwardAPI` 卷，Container 把卷挂载在 `/etc` 。
Container 需要翻译,只要不是明确的”Container  field“的表述，”Container “都建议翻译

2018-01-26 09:36 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +对于容器来说，有时可以获得关于它自己的信息而不和 Kubernetes 过度耦合非常有用。Downward API 允许容器获取有关自己或集群的信息，而不使用 Kubernetes 客户端
还是有点拗口，
有时可以获得关于它自己的信息而不和 Kubernetes 过度耦合非常有用 -> 有时在不和 Kubernetes 过度耦合的情况下获得关于它自己的信息非常有用

2018-01-26 09:36 UTC, lichuqiang commented on docs/tasks/inject-data-application/downward-api-volume-expose-pod-information.md
> +一个例子是假定一个已经存在的应用程序拥有有唯一的标识符个特定著名的环境变量，这个环境变量有唯一的标识符。一种可能性是包装应用程序，
拥有有唯一的标识符个特定著名的环境变量 -> 拥有一个特别的知名环境变量

2018-01-27 04:44 UTC, pigletfly commented
updated,and thanks @lichuqiang  for reviewing

2018-01-27 06:44 UTC, lichuqiang approved these changes

2018-01-27 06:44 UTC, lichuqiang commented
/lgtm

2018-01-28 09:27 UTC, merged