concepts-storage-volumes-pr-20180125
kubernetes/kubernetes-docs-zh pull request #205
Opened 2018-01-25 04:58 UTC by rootsongjc

Volumes translations

2018-01-25 09:24 UTC, xiaosuiba requested changes
请参考。
As this page is a critical one in the concepts catalog, PLEASE BE MORE CAREFUL AND CAUTIOUS!

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +title: Volume
这里是为什么要改变原标题？

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +容器磁盘上的文件的生命周期是短暂的，这就使得在容器中运行重要应用时会出现一些问题。首先，让容器崩溃时，kubelet 会重启它，但是容器中的文件讲丢失——容器以干净的状态（镜像最初的状态）重新启动。其次，在 `Pod` 中同时运行多个容器时，这些容器之间通常需要共享文件。Kubernetes 中的 `Volume` 抽象就很好的解决了这些问题。
让容器崩溃时 -> 当
讲丢失 -> 将

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +另一方面，Kubernetes 中的卷有明确的寿命——与封装它的 Pod 相同。所以，卷的生命比 Pod 中的所有容器都长，但个容器重启时数据仍然得意保存。当然，当 Pod 不再存在时，卷也将不复存在。也许更重要的是， Kubernetes 支持多种类型的卷，Pod 可以同时使用任意数量的卷。
得意 -> 得以
也许更重要的是， Kubernetes -> Kubernetes 前多余空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +卷的核心是目录，可能还包含了一些数据，可以通过 pod 中的容器来访问。该目录是如何形成的，支持该目录的介质以及其内容取决于所使用的特定卷类型。
形成的，-> 中文表并列的时候还是建议用顿号

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +要使用卷，需要为 pod 指定为卷（`spec.volumes` 字段）以及将它挂载到容器的位置（`spec.containers.volumeMounts` 字段）。
需要为 pod 指定为卷（`spec.volumes` 字段） -> 需要为 pod 指定提供怎样的卷（`spec.volumes` 字段）
以及将它挂载到容器的位置 -> 以及将它挂载到容器中的位置（this one up to you）

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +容器中的进程看到由其 Docker 镜像和卷组成的文件系统视图。 [Docker 镜像](https://docs.docker.com/userguide/dockerimages/)位于文件系统层次结构的根目录，任何卷都被挂载在镜像的指定路径中。卷无法挂载到其他卷上或与其他卷有硬连接。 Pod 中的每个容器都必须独立指定每个卷的挂载位置。
看到 -> 看到的是
 Pod 中 -> 多余空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`awsElasticBlockStore` 卷将Amazon Web Services（AWS）[EBS Volume](http://aws.amazon.com/ebs/) 挂载到您的容器中。不像 `emptyDir`，删除 Pod 时删除 EBS 卷的内容，只是卸载卷。这意味着 EBS 卷可以预先填充数据，并且可以在数据包之间“切换”数据。
Amazon Web 之前差空格
不像 `emptyDir`，删除 Pod 时删除 EBS 卷的内容，只是卸载卷 -> 这句有歧义
与  `emptyDir` 类型会在删除 Pod 时被清除不同，EBS 卷的的内容会保留下来，仅仅是被卸载。

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须使用 `aws ec2 create-volume` 或 AWS API 创建 EBS 卷，才能使用它。
遗漏 {: .caution} 标记

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +#### 创建一个EBS卷
EBS 前后空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +更多细节可以在[这里](https://github.com/kubernetes/examples/tree/{{page.githubbranch}}/staging/volumes/azure_disk/README.md)找到。
[这里] 链接前后需要空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`azureFile` 用于将 Microsoft Azure FIle Volume（SMB 2.1 和 3.0）挂载到 Pod 中。
FIle 笔误

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +更多细节可以在[这里](https://github.com/kubernetes/examples/tree/{{page.githubbranch}}/staging/volumes/azure_file/README.md)找到。
空格，同上

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`cephfs` 卷允许将现有的 CephFS 卷挂载到您的容器中。不像 `emptyDir`，当删除 Pod 时被删除，`cephfs` 卷的内容将被保留，卷仅仅是被卸载。这意味着 CephFS 卷可以预先填充数据，并且可以在数据包之间“切换”数据。 CephFS 可以被多个写设备同时挂载。
Unlike……一句的语法与上文 EBS 的相识，请统一成一种翻译方式

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +有关更多详细信息，请参见[CephFS示例](https://github.com/kubernetes/examples/tree/{{page.githubbranch}}/staging/volumes/cephfs/)。
链接前后空格
下同，请全文检索并修改，后面不再单独提出

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +- `driver`：一个字符串值，指定要使用的卷驱动程序的名称。必须少于 63 个字符，并以一个字符开头。驱动程序名称可以包含 “。”、“ - ”、“_” 或数字。
特殊字符如 `_` 请用 `` inline-block 括起来，不然会影响后面格式

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`downwardAPI` 卷用于使应用程序可用的 API 数据下沉。它挂载一个目录，并将请求的数据写入纯文本文件。
卷用于使应用程序可用的 API 数据下沉 -> 卷用于使向下 API 数据（downward API data）对应用程序可用

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须配置 FC SAN 区域划分，以便将这些 LUN（卷）预先分配给目标 WWN，以便 Kubernetes 主机可以访问它们。
以便将这些 LUN -> 并预先将这些 LUN（卷）分配并屏蔽到目标 WWN

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +参考 [FC  示例](https://github.com/kubernetes/examples/tree/{{page.githubbranch}}/staging/volumes/fibre_channel)获取详细信息。
多余空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +- 那些虚拟机需要在与 PD 一样在 GCE 项目和区域中
一样在 -> 在相同的

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`gitRepo` 卷是一个可以做为卷插件的例子。它会挂载一个空目录并将 git 存储库克隆到您的容器中。将来，这样的卷可能会转移到一个更加分离的模型，而不是为每个这样的用例扩展 Kubernetes API。
是一个可以做为卷插件的例子 -> 是一个可以演示卷插件功能的示例

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`glusterfs` 卷允许将 [Glusterfs](http://www.gluster.org)（一个开放源代码的网络文件系统）卷挂载到您的群集中。与删除 Pod 时删除的 `emptyDir` 不同，`glusterfs` 卷的内容将被保留，而卷仅仅被卸载。这意味着 glusterfs 卷可以预先填充数据，并且可以在数据包之间“切换”数据。 GlusterFS 可以同时由多个写入挂载。
群集 -> 集群，请全文替换

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须先运行自己的 GlusterFS 安装，才能使用它。
您必须先运行自己的 GlusterFS 安装，才能使用它 ->
在使用之前，您必须先自行安装 GlusterFS

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`hostPath` 卷将主机节点的文件系统中的文件或目录挂载到集群中。该功能大多数 Pod 都用不到，但它为某些应用程序提供了一个强大的退出方法。
escape hatch 这里翻译为“出路，办法”
一种强大的解决方案/有效的解决办法

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +| `BlockDevice`       | 给的路径下必须窜爱块设备                             |
窜爱 -> 存在

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +注意使用卷的类型，因为：
使用这种卷类型时请注意

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +这个 alpha 功能要求启用 `PersistentLocalVolumes` 功能门。
feature gate 不用翻译
下同

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +与 HostPath 卷相比，local 卷可以以持久的方式使用，而无需手动将 pod 调度到节点上，因为系统通过查看 PersistentVolume 上的节点关联性来了解卷的节点约束。
系统通过 -> 系统会通过

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +所有来源都必须在与 pod 相同的命名空间中。有关更多详细信息，请参阅[ all-in-one 卷设计文档](https://github.com/kubernetes/community/blob/{{page.githubbranch}}/contributors/design-suggestions/node/all-in-one-volume.md)。
[ all 多余空格

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`portworxVolume `是一个弹性块存储层，与 Kubernetes 超级聚合。Portwork 指纹存储在服务器中，基于功能的分层，以及跨多个服务器聚合容量。 Portworx 在虚拟机或裸机 Linux 节点上运行。
`portworxVolume `是一个弹性块存储层，与 Kubernetes 超级聚合 
->
`portworxVolume`  是一个与 Kubernetes 一起，以超融合模式运行的弹性块存储层

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +以下是一个引用预先配置的 PortworxVolume 的示例窗格：
示例窗格 -> 示例 pod

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须先运行自己的 Ceph 安装，然后才能使用 RBD。
您必须先运行自己的 Ceph 安装 -> 您必须先自行安装 Ceph

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须先安装现有的 ScaleIO 集群，并使用创建的卷运行，然后才能使用它们。
您必须先安装现有的 ScaleIO 集群，并使用创建的卷运行
->
您必须有一个已经配置好的  ScaleIO 集群，并和创建的卷一同运行

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`秘密` 卷用于将敏感信息（如密码）传递到 pod。您可以将 secret 存储在 Kubernetes API 中，并将它们挂载为文件，以供 Pod 使用，而无需直接连接到 Kubernetes。 `secret` 卷由 tmpfs（一个 RAM 支持的文件系统）支持，所以它们永远不会写入非易失性存储器。
secret 不翻译，下同

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须在每个要访问 StorageOS 卷的节点上运行 StorageOS 容器，或者为该池提供存储容量。有关安装说明，请参阅 [StorageOS文档](https://docs.storageos.com)。
有关安装说明 -> 相关的安装说明

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +要启用此功能，请在 `--feature-gates` 命令行选项中指定 `MountPropagation = true`。启用时，容器的 `volumeMounts` 字段有一个新的 `mountPropagation` 子字段。它的价值是：
价值是 -> 值为

2018-01-25 09:24 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +- 以[使用持久化卷来部署 WordPress 和 MySQL](/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/) 为例。
参照 [使用持久化卷来部署 WordPress 和 MySQL](/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/) 示例。

2018-01-25 09:40 UTC, rootsongjc commented on docs/concepts/storage/volumes.md
> +title: Volume
标题需要用复数吗？

2018-01-25 09:50 UTC, rootsongjc commented on docs/concepts/storage/volumes.md
> +更多细节可以在[这里](https://github.com/kubernetes/examples/tree/{{page.githubbranch}}/staging/volumes/azure_disk/README.md)找到。
链接前后也需要空格吗？我之前好像都没加啊。

2018-01-26 00:48 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +title: Volume
英文类文章的标题，实词一般首字母大写，用复数表示
鉴于这个地方其实保留了原文，而且这个目录内不止这一篇文章，为了保持和其它文章统一，建议还是保留复数。

2018-01-26 01:00 UTC, xiaosuiba requested changes
请参考。

2018-01-26 01:00 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +另一方面，Kubernetes 中的卷有明确的寿命——与封装它的 Pod 相同。所以，卷的生命比 Pod 中的所有容器都长，但个容器重启时数据仍然得以保存。当然，当 Pod 不再存在时，卷也将不复存在。也许更重要的是， Kubernetes 支持多种类型的卷，Pod 可以同时使用任意数量的卷。
但个容器重启时数据仍然得以保存 -> 当这个容器重启时数据仍然得以保存

2018-01-26 01:00 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +`downwardAPI` 卷用于使应用程序可用的向下 API 数据（downward API data）对应用程序可用。它挂载一个目录，并将请求的数据写入纯文本文件。
卷用于使应用程序可用的向下 API 数据（downward API data）对应用程序可用
->
卷用于使向下 API 数据（downward API data）对应用程序可用

2018-01-26 01:00 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +| `BlockDevice`       | 给的路径下必须存在块设备                             |
给的路径下必须存在块设备
->
给定

2018-01-26 01:00 UTC, xiaosuiba commented on docs/concepts/storage/volumes.md
> +**重要提示**：您必须在每个要访问 StorageOS 卷的节点上运行 StorageOS 容器，或者为该池提供存储容量。相关的额安装说明，请参阅 [StorageOS文档](https://docs.storageos.com)。
相关的额安装说明
->
相关的安装说明

2018-01-26 03:09 UTC, rootsongjc commented on docs/concepts/storage/volumes.md
> +title: Volume
OK，那我就保留复数吧。

2018-01-28 09:34 UTC, merged