kubeadm-alpha-phase-kubeconfig-scheduler-pr-2018-3-21
kubernetes/kubernetes-docs-zh pull request #300
Opened 2018-03-21 04:52 UTC by okzhchy

2018-03-22 08:33 UTC, chentao1596 requested changes
根据原来大家讨论的一些情况，中英文之间请用空格进行隔开，谢谢！！

2018-03-22 08:33 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_scheduler.md
> +title: 生成kubeconfig文件给调度器使用
kubeconfig 前后请增加空格，区分中英文的内容

2018-03-22 08:33 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_scheduler.md
> +cn-approvers-update:
这里的 ”cn-approvers-update:“ 和 ”cn-reviewers“ 没有必要了

2018-03-22 08:33 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_scheduler.md
> +<<<<<<< HEAD
这里应该是文件冲突多余的内容吧？不过这里不影响最终的文件展示，只是我有点强迫症了，^_^

2018-03-22 08:33 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_scheduler.md
> +      --cert-dir string                      证书存储路径 (默认值 "/etc/kubernetes/pki")
括号前面建议不要空格，可以使用中文括号

2018-03-22 08:33 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_kubeconfig_scheduler.md
> +      --apiserver-advertise-address string   API server可访问的IP地址
建议这两个参数调整下主谓关系（apiserver-advertise-address和apiserver-bind-port），含义应该是表示通过参数指定的地址和端口可以访问 apiserver，但是从现在翻译的内容来看，感觉是说 API server去访问别人

2018-03-22 13:11 UTC, okzhchy commented
@chentao1596 非常感谢指导

2018-03-23 07:35 UTC, chentao1596 reviewed
请合并 commit，其它 LGTM
@markthink

2018-03-25 12:10 UTC, merged