kubeadm-alpha-phase-certs-all-pr-2018-3-21
kubernetes/kubernetes-docs-zh pull request #304
Opened 2018-03-21 07:13 UTC by okzhchy

2018-03-22 08:57 UTC, chentao1596 requested changes
中英文之间请用空格进行隔开，谢谢！！

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/README.md
> +<!--
该文件的翻译，已经提交了吧？
ref: https://github.com/kubernetes/kubernetes-docs-cn/pull/303

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
> +title: 生成kubeconfig文件给调度器使用
个人觉得不应该去修改文档的原有结构，这里没有必要强行增加 title 的内容，当然，这里 title 的内容貌似不对哦

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
> +为集群中（包括节点）每个模块生成一个自签名的CA身份，客户端认证将被各种不同模块所使用。
个人理解这句翻译不对，
 Generates a self-signed CA be used by various components，我觉得这样子连起来是一个翻译内容
provision identities for each component in the cluster (including nodes) and client certificates，这个应该是翻译的第二个内容

比如：生成自签名 CA，为集群中的每个组件（包括节点）和客户端证书提供标识，供各种组件使用。

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
> +如果已有的认证和私钥对都存在，kubeadm跳过生成步骤而使用现有的文件。
已有的
-》
给定的

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
> +      --apiserver-advertise-address string      API server可访问的IP地址，应用于API server服务证书
建议这个参数调整下主谓关系（apiserver-advertise-address），含义应该是表示通过参数指定的地址可以访问 apiserver，但是从现在翻译的内容来看，感觉是说 API server去访问别人

2018-03-22 08:57 UTC, chentao1596 commented on docs/reference/setup-tools/kubeadm/generated/kubeadm_alpha_phase_certs_all.md
> +      --config string                           kubeadm配置文件路径 (警告: 使用配置文件处于实验阶段)
括号前面建议不要空格，可以使用中文括号

2018-03-22 13:25 UTC, okzhchy commented
感谢指导

2018-03-23 07:33 UTC, chentao1596 requested changes
还有两点需要修改下：
1，README.md文件在其它PR中已经提交（我看了下你那个提交，应该是由于你那个PR是在你的master分支里面创建的，所以这里也更新了，所以最好每个PR单独一个branch），这里不应该再提交，否则可能冲突了
2，第二个文件，我觉得还是把title部分去掉比较好，跟原文保持一致
希望对你有所帮助，^_^，谢谢！

2018-03-23 09:36 UTC, okzhchy commented
谢谢！确实是这样。第一个问题，那我应该怎么解决？

2018-03-24 01:33 UTC, chentao1596 commented
对于不需要提交的文件，我一般都是先备份自己修改的文件，然后尝试直接从master（kubernetes-doc-cn的master）获取原文覆盖，然后重新提交回去，那个文件就不会发生变更了，建议可以这样子尝试下，^_^！

2018-03-25 04:20 UTC, closed without merging

2018-03-25 04:20 UTC, okzhchy commented
避免冲突，已经重新提交PR