translate encrypt-data.md
kubernetes/kubernetes-docs-zh pull request #518
Opened 2018-08-24 03:15 UTC by tianshapjq

translate encrypt-data.md

2018-08-26 13:29 UTC, markthink reviewed
原始的英文信息呢？参考翻译规范要求..

2018-08-26 13:30 UTC, markthink commented
@tianshapjq  译文里没有对应的原始英文..参考翻译规范..

2018-08-29 03:51 UTC, tengqm requested changes

2018-08-29 03:51 UTC, tengqm commented on content/cn/docs/tasks/administer-cluster/encrypt-data.md
> +title: 通过 Rest 加密 Secret 数据
data in rest 的意思是静态的、不被到处复制、传播的数据
相对地，data in motion 的意思是指在网络上传播、处于移动状态中的数据。

本文的翻译中对 rest 的理解有问题。

2018-08-29 06:27 UTC, tianshapjq commented
@markthink 不好意思，我是看en目录下有些已经翻译的没有带原文，以为规范改了。稍后提交修改。

2018-09-02 13:15 UTC, markthink commented
@tianshapjq 没关系，欢迎更新..

2018-09-03 06:23 UTC, tengqm approved these changes
/lgtm

2018-09-03 06:23 UTC, tianshapjq commented
@tengqm 已更新，麻烦帮忙看看，谢谢~

2018-09-10 15:10 UTC, merged