translate audit.md
kubernetes/kubernetes-docs-zh pull request #528
Opened 2018-08-26 14:59 UTC by tianshapjq

translate audit.md to Chinese

2018-08-29 05:53 UTC, tengqm requested changes

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +title: Auditing
title should be translated as well?

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +Kubernetes 审计功能提供了与安全相关的按时间顺序排列的记录集，记录单个用户、管理员或系统其他组件影响系统的活动顺序。
> sequence of activities

活动序列

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 为什么发生？
on what did it happen

请重翻

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 它将产生什么后果？
to where was it going

请重翻

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +您可以在 [设计方案][auditing-proposal] 中找到更多详细信息。
这句的来源？

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +每个请求都可以用相关的 "stage" 记录。已知的 stage 有：
针对每个请求都可以记录其相关的 "stage"

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +- `RequestReceived` - 事件的 stage 将在审计处理器接收到请求后，并且在委托给其余处理器之前生成。
审计处理器接收到请求但尚未将其委托给其他处理器之前，所生成的事件对应此 stage

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +在这两种情况下，审计事件结构均由 `audit.k8s.io` API 组中的 API 定义。当前版本的 API 是 [`v1beta1`][auditing-api]。
API 的当前版本是 ...

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +**注意：** 在 patch 请求的情况下，请求的消息体需要是一个 JSON 串指定 patch 操作，而不是一个完整的 Kubernetes API 对象 JSON 串。
> 请求的消息体需要是一个 JSON 串指定 patch 操作，而不是一个完整的 Kubernetes API 对象 JSON 串。

请求的消息体是一个包含 patch 操作的 JSON 数组而不是一个包含完整的 Kubernetes API 对象的 JSON 对象。

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +- `--audit-log-path` 指定用来写入审计事件的日志文件路径。不指定此标志会禁用日志后端。`-` 意味着标准化
> standard out 

标准输出

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +### Batching
> Batching

关于批处理

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +  - `blocking` - 阻止 API server 处理每个单独事件的响应。
在处理各个事件时，阻塞 API 服务器对请求做出响应

2018-08-29 05:53 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> +## 日志选择器示例
Collector 是收集器或采集器

2018-09-03 14:35 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 它发生了什么？
操作发生在哪个对象上面？

2018-09-03 14:37 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 它去哪儿了？
操作的后续动作是什么？

2018-09-03 14:38 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 它发生了什么？
活动发生在哪个（些）对象上？

2018-09-03 14:39 UTC, tengqm commented on content/cn/docs/tasks/debug-application-cluster/audit.md
> + - 它去哪儿了？
活动的后续处理行为是什么？

2018-09-11 03:22 UTC, tianshapjq commented
@tengqm thanks for you review! new commit, PTAL~

2018-09-11 06:02 UTC, tengqm commented
@tianshapjq Looks like you are committing the "content/cn/docs/tutorials/clusters/apparmor.md" file by accident? Please remove it from your PR.

2018-09-11 06:22 UTC, tianshapjq commented
@tengqm sorry about that! already removed.

2018-09-11 07:18 UTC, tengqm commented
/lgtm

2018-09-12 12:43 UTC, tengqm commented
/approve

2018-09-12 12:45 UTC, merged