2018-07-09-IPVS-In-Cluster-Load-Balancing-pr-2018-08-28
kubernetes/kubernetes-docs-zh pull request #533
Opened 2018-08-28 02:21 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-02 13:28 UTC, markthink commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +随着Kubernetes的使用增长，其资源的可扩展性变得越来越重要。特别是，服务的可扩展性对于运行大型工作负载的开发人员/公司采用Kubernetes至关重要。
中英文要有留白

2018-09-02 13:29 UTC, markthink commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +    ...
代码块不建议注释..

2018-09-02 13:30 UTC, markthink commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +  设置名称                          	成员                                      	用法
对于没有翻译内容的代码块不建议注释，这里是例外，此代码块可以注释，因为有要翻译的描述内容。

2018-09-02 13:31 UTC, markthink reviewed
总体都很棒，需要注意格式规范..

2018-09-12 04:02 UTC, hanjiayao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +根据 Kubernetes 1.11 发布的博客文章, 我们宣布基于 IPVS 的集群内部服务负载均衡已达到 一般可用性。 在这篇博客中，我们将带您深入了解该功能。
“已达到” “一般可用”之间空格须去掉

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +IPVS (IP Virtual Server)是在 Netfileter 上层构建的，并作为 Linux 内核的一部分，实现传输层负载均衡。
s/Netfileter/Netfilter

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +IPVS 集成在 LVS（Linux 虚拟服务器）中，它在主机上运行，并在物理服务器集群前作为负载均衡器。IPVS 可以将基于 TCP 和 UDP 服务的请求定向到真实服务器，并使真实服务器的服务在单个IP地址上显示为虚拟服务。 因此，IPVS 自然支持 Kubernetes 服务。
`LVS（Linux 虚拟服务器）`这种简称最好把原文也列上，我印象中一般是写成这种形式：
`LVS（Linux Virtual Server，Linux 虚拟服务器）`

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +参数r: --ipvs-min-sync-period 刷新 IPVS 规则的最小间隔时间间隔（例如'5s'，'1m'）。 必须大于0。
`参数r:` 多了一个`r`

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +  KUBE-NODE-PORT-LOCAL-UDP      	NodePort 类型服务 UDP 端口 使用 externalTrafficPolicy=local	接受数据包到NodePort服务 使用 externalTrafficPolicy=local
上面这些内容实际预览时格式有点乱，建议翻译后格式化为表格形式

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +目前，本地脚本，GCE 脚本和 kubeadm 支持通过导出环境变量（KUBE_PROXY_MODE = ipvs）或指定标志（--proxy-mode = ipvs）来切换 IPVS 代理模式。 在运行IPVS 代理之前，请确保已安装 IPVS 所需的内核模块。
这里及下面的等号左右不建议加空格

2018-09-12 05:51 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +参与 Kubernetes 的最简单方法是加入众多[特别兴趣小组]（https://github.com/kubernetes/community/blob/master/sig-list.md）（SIG）中与您的兴趣一致的小组。 你有什么想要向 Kubernetes 社区广播的吗？ 在我们的每周[社区会议]（https://github.com/kubernetes/community/blo
这里附近的链接格式不准确，请预览后确认并修改一下。

2018-09-18 01:42 UTC, xiangpengzhao requested changes
链接格式仍然需要修改一下 :)

2018-09-18 01:42 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +参与 Kubernetes 的最简单方法是加入众多[特别兴趣小组]（https://github.com/kubernetes/community/blob/master/sig-list.md）（SIG）中与您的兴趣一致的小组。 你有什么想要向 Kubernetes 社区广播的吗？ 在我们的每周[社区会议]（https://github.com/kubernetes/community/blo
当前的链接内容预览结果：
![image](https://user-images.githubusercontent.com/15881573/45659426-05c95780-bb27-11e8-9056-ab11379b7830.png)

2018-09-20 03:07 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +在[Slack]（http://slack.k8s.io/)上与社区聊天
更新后的这些链接仍然有问题，需要注意区分中英文的括号

2018-09-20 09:15 UTC, xiangpengzhao requested changes

2018-09-20 09:15 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-07-09-IPVS-In-Cluster-Load-Balancing.md
> +在[Stack Overflow]上发布问题（或回答问题）（http://stackoverflow.com/questions/tagged/kubernetes)
链接似乎还是有问题。看情形应该是链接的左圆括号用的是中文括号。建议在修改完之后在本地用markdown工具先预览一下，确认无误后再提交 :)

![image](https://user-images.githubusercontent.com/15881573/45808548-94410300-bcf8-11e8-9a8c-c3c20ec0589a.png)

2018-09-22 09:42 UTC, tengqm commented
/lgtm

2018-09-23 12:07 UTC, merged