Congfairy patch 2
kubernetes/kubernetes-docs-zh pull request #534
Opened 2018-08-28 02:33 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-08-29 03:26 UTC, tengqm requested changes

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +Apache Airflow是DevOps“Configuration As Code”理念的一种实现。 Airflow允许用户使用简单的Python对象DAG（定向非循环图）启动多步骤流水线。 您可以在易于阅读的UI中定义依赖项，以编程方式构建复杂的工作流，并监视调度的作业。
DAG 是有向无环图的缩写

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +Apache Airflow是DevOps“Configuration As Code”理念的一种实现。 Airflow允许用户使用简单的Python对象DAG（定向非循环图）启动多步骤流水线。 您可以在易于阅读的UI中定义依赖项，以编程方式构建复杂的工作流，并监视调度的作业。
依赖项 -> 依赖关系

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +在我们进一步发展之前，我们应该澄清Airflow中的[Operator]（https://airflow.apache.org/concepts.html#operators）是一个任务定义。 当用户创建DAG时，他们将使用像“SparkSubmitOperator”或“PythonOperator”这样的operator分别提交/监视Spark作业或Python函数。 Airflow附带了Ap
> 在我们进一步发展之前

在进一步讨论之前

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +Airflow用户一直在寻找更易于管理部署和ETL流的方法。 在增加监控的同时，任何解耦流程的机会都可以减少未来的停机等问题。 以下是Airflow Kubernetes Operator提供的性能：
> 性能

好处

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +* 使用kubernetes秘密以增加安全性：
Secret 不要翻译

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +Kubernetes Operator使用[Kubernetes Python客户端]（https://github.com/kubernetes-client/Python)生成由APIServer处理的请求（1）。 然后，Kubernetes将使用您定义的需求启动您的pod（2）。 图像将所有必要的环境变量，秘密和依赖项进行加载，制定单个命令。 一旦启动作业，operator只需要监视跟踪日
> 图像...

映像文件中将加载

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +Kubernetes Operator使用[Kubernetes Python客户端]（https://github.com/kubernetes-client/Python)生成由APIServer处理的请求（1）。 然后，Kubernetes将使用您定义的需求启动您的pod（2）。 图像将所有必要的环境变量，秘密和依赖项进行加载，制定单个命令。 一旦启动作业，operator只需要监视跟踪日
> 制定单个命令

执行单个命令

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +```Python
下面这段代码不要空太多行

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +虽然这个例子只使用基本图像，但Docker的神奇之处在于，这个相同的DAG可以用于您想要的任何图像/命令配对。 以下是推荐的CI / CD管道，用于在Airflow DAG上运行生产就绪代码。
> 图像

映像

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +```Python
代码段不要很多空行

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +由于Kubernetes运营商尚未发布，我们尚未发布官方[helm]（https://helm.sh/ 图表或operator（但两者目前都在进行中）。 但是，我们在下面列出了基本部署的说明，并且正在积极寻找测试人员来尝试这一新功能。 要试用此系统，请按以下步骤操作：
注意链接的半角/全角字符，全角字符无法生成有效链接

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +为了运行这个基本部署，我们正在选择我们目前用于Kubernetes Executor的集成测试脚本（将在本系列的下一篇文章中对此进行解释）。 要启动此部署，请运行以下三个命令：
部署不要翻译，直接用 Deployment

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +此脚本将对Airflow主分支代码进行压缩，以根据Airflow分布构建Docker容器
严格地说，tar 操作是打包，并不进行压缩

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +此脚本将对Airflow主分支代码进行压缩，以根据Airflow分布构建Docker容器
Airflow distribution： Airflow 的发行文件

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +现在，Airflow UI将存在于http：// localhost：8080上。 要登录，只需输入airflow /airflow，您就可以完全访问Airflow Web UI。
请注意半角/全角字符

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +＃那么我什么时候可以使用它？
请注意半角/全角字符

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +＃ 参与其中
请注意半角/全角字符

2018-08-29 03:26 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> + *在kubernetes.slack.com上的＃sig-big-data找到我们。
请注意半角/全角字符

2018-08-29 06:23 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +由于Kubernetes运营商尚未发布，我们尚未发布官方[helm] https://helm.sh/ 图表或operator（但两者目前都在进行中）。 但是，我们在下面列出了基本部署的说明，并且正在积极寻找测试人员来尝试这一新功能。 要试用此系统，请按以下步骤操作：
helm 是一个链接，删除括号之后链接会非法

2018-08-29 06:23 UTC, tengqm commented on content/cn/blog/_posts/2018-06-28-Airflow-Kubernetes-Operator.md
> +为了运行这个基本Ddeployment，我们正在选择我们目前用于Kubernetes Executor的集成测试脚本（将在本系列的下一篇文章中对此进行解释）。 要启动此部署，请运行以下三个命令：
拼写

2018-09-02 13:32 UTC, markthink commented
@congfairy 需要根据 tengqm 的意见修复一下，谢谢。

2018-09-10 09:21 UTC, congfairy commented
已经按照要求修改

2018-09-10 15:30 UTC, merged