Congfairy patch 3
kubernetes/kubernetes-docs-zh pull request #535
Opened 2018-08-28 02:36 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-02 13:33 UTC, markthink commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +今天的发布继续推进Kubernetes的成熟度，可扩展性和灵活性，标志着团队在过去一年中努力研发的功能取得了重大进展。 这个最新版本涵盖网络的关键功能，开启了SIG-API Machinery和SIG-Node的两个主要功能，用于beta测试，并继续增强存储功能，这些功能一直是过去两个版本的焦点。 此版本中的功能使得将任何基础架构，云或预置部署加入Kubernetes系统的可能性越来越大。
中英文要有间隔空白

2018-09-02 13:34 UTC, markthink commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +
中英文间隔过长

2018-09-02 13:34 UTC, markthink reviewed
总体上很不错，格式上需要规范一下..

2018-09-12 05:21 UTC, tengqm requested changes

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +
> graduate to general availability

意思是说前面说的功能特性已经成熟，成为 GA 正式发布版本……

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +我们很高兴地宣布推出2018年第二个发型版本，Kubernetes 1.11！
> 发型版本

翻译后请检查类似问题

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +今天的发布继续推进Kubernetes的成熟度，可扩展性和灵活性，标志着团队在过去一年中努力研发的功能取得了重大进展。 这个最新版本涵盖网络的关键功能，开启了SIG-API Machinery和SIG-Node的两个主要功能，用于beta测试，并继续增强存储功能，这些功能一直是过去两个版本的焦点。 此版本中的功能使得将任何基础架构，云或预置部署加入Kubernetes系统的可能性越来越大。
> graduates key features in networking

这里指的是网络方面的某些功能特性已经成熟，不再是实验性功能特性。

> on-premise

是指在客户自己的机房/数据中心的资产或服务，怎么能翻译成“预置部署”呢？

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +在此版本中，[基于IPVS的集群内服务负载均衡]（https://github.com/kubernetes/features/issues/265 ）已稳定运行。 IPVS（IP虚拟服务器）提供高性能的内核负载均衡，具有比iptables更简单的编程接口。 此更改为包含Kubernetes服务模型的集群范围的分布式负载均衡器提供了更好的网络吞吐量，更好的编程延迟和更高的可伸缩性限制。 IPVS
“[]()" 是 markdown 中超链接的写法，翻译的时候一定不能将这些符号改成全角字符。

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +在此版本中，[基于IPVS的集群内服务负载均衡]（https://github.com/kubernetes/features/issues/265 ）已稳定运行。 IPVS（IP虚拟服务器）提供高性能的内核负载均衡，具有比iptables更简单的编程接口。 此更改为包含Kubernetes服务模型的集群范围的分布式负载均衡器提供了更好的网络吞吐量，更好的编程延迟和更高的可伸缩性限制。 IPVS
“production traffic" 不应翻译成“大量流量”

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +[CoreDNS]（https://coredns.io ）现在可用作[集群DNS附加选项]（https://github.com/kubernetes/features/issues/427 ），并且是使用kubeadm时的默认选项。 CoreDNS是一个灵活，可扩展的权威DNS服务器，可直接与Kubernetes API集成。 CoreDNS比以前的DNS服务器具有更少的移去的部件，因为它是
“moving parts" 指的是一个架构中经常发生变动且其变化难以跟踪的组件，不是“移去的部件”

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +此功能可以在实时集群中推出新的Kubelet配置。 目前，Kubelet是通过命令行标志配置的，这使得在正在运行的集群中更新Kubelet配置变得很困难。 有了这个测试版功能，[用户可以通过API服务器在实时集群中配置Kubelet]（https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/）。
live cluster 指的是运行中、使用中的集群，不是“实时集群”

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +自定义资源定义不再局限于定义单个版本的自定义资源，这是一种难以解决的限制。现在，通过此beta [feature]（https://github.com/kubernetes/features/issues/544 ），可以定义多个版本的资源。将来，这将扩展到支持一些自动转换;目前，此功能允许自定义资源作者“通过安全更改进行促销，例如： v1beta1到v1，“并为有更改的资源创建迁移路径。
promote 在此上下文中是“升级版本”的意思，不是“促销”

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +容器存储接口（CSI）是过去几个版本中的一个主要话题。 在转向[beta 1.10]（https://github.com/container-storage-interface/spec/blob/master/spec.md ）之后，1.11版本继续通过许多功能增强CSI。 1.11版本为CSI添加了对原始块体积的alpha支持，将CSI与新的kubelet插件注册机制集成在一起，并且更容易
beta in 1.10 不是 beta 1.10

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +容器存储接口（CSI）是过去几个版本中的一个主要话题。 在转向[beta 1.10]（https://github.com/container-storage-interface/spec/blob/master/spec.md ）之后，1.11版本继续通过许多功能增强CSI。 1.11版本为CSI添加了对原始块体积的alpha支持，将CSI与新的kubelet插件注册机制集成在一起，并且更容易
raw block volumes => 原生块存储卷

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +容器存储接口（CSI）是过去几个版本中的一个主要话题。 在转向[beta 1.10]（https://github.com/container-storage-interface/spec/blob/master/spec.md ）之后，1.11版本继续通过许多功能增强CSI。 1.11版本为CSI添加了对原始块体积的alpha支持，将CSI与新的kubelet插件注册机制集成在一起，并且更容易
secret 是 kubernetes 中一种资源的名称，不要翻译成“秘密”

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +支持[动态最大卷数]（https://github.com/kubernetes/features/issues/554 ）已作为alpha功能引入。此新功能使in-卷插件能够指定可附加到节点的最大卷数，并允许限制根据节点类型而变化。以前，这些限制是通过环境变量进行硬编码或配置的。
in-tree volume plugins 需要重新翻译

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +StorageObjectInUseProtection功能现在是稳定的，并且可以防止删除绑定到持久卷声明和[持久卷声明]的[持久卷]（https://github.com/kubernetes/features/issues/499 ） pod正在使用：（http://github.com/kubernetes/features/issues/498 ）。此安全措施有助于防止删除当前绑定到活动
that are being used by a pod => 这句是修饰语

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +StorageObjectInUseProtection功能现在是稳定的，并且可以防止删除绑定到持久卷声明和[持久卷声明]的[持久卷]（https://github.com/kubernetes/features/issues/499 ） pod正在使用：（http://github.com/kubernetes/features/issues/498 ）。此安全措施有助于防止删除当前绑定到活动
活动窗格？

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +＃＃ 可用性
这里的 # 号是 markdown 标题的标记，不要改成全角

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +## Project Velocity
项目进展情况

2018-09-12 05:21 UTC, tengqm commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +* 纽约时报，被称为记录报纸，[移出其数据中心并进入公共云]（https://kubernetes.io/case-studies/newyorktimes/ ）借助于Google Cloud Platform和Kubernetes。此举意味着Kubernetes的交付速度显着提高，从45分钟缩短到几秒钟。
newspaper of record 翻译错误

2018-09-13 09:01 UTC, hanjiayao commented on content/cn/blog/_posts/2018-06-26-kubernetes-1.11-release-announcement.md
> +## 4天特色博客系列
4天功能博客系列

2018-09-18 05:05 UTC, tengqm commented
/lgtm

pending approve due to conflicts.

2018-09-23 12:09 UTC, markthink commented
@congfairy 文件有冲突，麻烦解决一下。

2018-10-15 21:58 UTC, closed without merging