Congfairy patch 4
kubernetes/kubernetes-docs-zh pull request #536
Opened 2018-08-28 02:39 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-02 13:35 UTC, markthink commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +[Kubeflow]（https://github.com/kubeflow/kubeflow）提供了一种在Kubernetes上轻松部署机器学习基础架构的简单方法。 Kubeflow团队需要一个代理，为Kubeflow中使用的各种服务提供认证和路由的中心点，其中许多服务本质上都是短暂的。
中英文混排需要空格间隔..

2018-09-12 12:22 UTC, tengqm requested changes

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +Kubernetes 可以轻松部署由许多微服务组成的应用程序，但这种架构的关键挑战之一是动态地将流量路由到这些服务中的每一个。 一种方法是 [Ambassador]（https://www.getambassador.io ），这是一个基于[Envoy Proxy]（https://www.envoyproxy.io ）构建的Kubernetes本地开源API网关。Ambassador专为动态环
> services may come and go frequently
服务可能会被频繁地创建和删除

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +Ambassador 通常作为 Kubernetes 部署安装，也可以作为 Helm 图表使用。 要配置 Ambassador ，请使用 Ambassador 注释创建 Kubernetes 服务。 这是一个配置 Ambassador，将请求路由到/ httpbin /公共 httpbin.org 服务的示例：
Deployment 不要翻译

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +Ambassador 通常作为 Kubernetes 部署安装，也可以作为 Helm 图表使用。 要配置 Ambassador ，请使用 Ambassador 注释创建 Kubernetes 服务。 这是一个配置 Ambassador，将请求路由到/ httpbin /公共 httpbin.org 服务的示例：
Chart 不要翻译

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +Ambassador 通常作为 Kubernetes 部署安装，也可以作为 Helm 图表使用。 要配置 Ambassador ，请使用 Ambassador 注释创建 Kubernetes 服务。 这是一个配置 Ambassador，将请求路由到/ httpbin /公共 httpbin.org 服务的示例：
“/ httpbin /” 中间不应该有空格

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +Ambassador 通常作为 Kubernetes 部署安装，也可以作为 Helm 图表使用。 要配置 Ambassador ，请使用 Ambassador 注释创建 Kubernetes 服务。 这是一个配置 Ambassador，将请求路由到/ httpbin /公共 httpbin.org 服务的示例：
“将请求路由到/ httpbin /公共 httpbin.org 服务” 这句重翻

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +
yaml里面不要有额外多余的空行

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +
不太理解为什么留这么多空行 ... review 很困难

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +通过 Ambassador，Kubeflow 可以使用 Kubernetes 注释轻松管理路由。 Kubeflow 配置单个入口对象，将流量定向到 Ambassador，然后根据需要创建具有 Ambassador注释的服务，以将流量定向到特定后端。例如，在部署 TensorFlow 服务时，Kubeflow 会创建并注释 K8s 服务，以便在https：// <ingress host> / m
Ingress 不要翻译

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +通过 Ambassador，Kubeflow 可以使用 Kubernetes 注释轻松管理路由。 Kubeflow 配置单个入口对象，将流量定向到 Ambassador，然后根据需要创建具有 Ambassador注释的服务，以将流量定向到特定后端。例如，在部署 TensorFlow 服务时，Kubeflow 会创建并注释 K8s 服务，以便在https：// <ingress host> / m
URL 中不要有空格

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +通过 Ambassador，Kubeflow 可以使用 Kubernetes 注释轻松管理路由。 Kubeflow 配置单个入口对象，将流量定向到 Ambassador，然后根据需要创建具有 Ambassador注释的服务，以将流量定向到特定后端。例如，在部署 TensorFlow 服务时，Kubeflow 会创建并注释 K8s 服务，以便在https：// <ingress host> / m
最后一句要重新组织

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +如果您有兴趣将 Ambassador 用作 API 网关或 Kubernetes 入口解决方案，请查看[Ambassador入门指南]（https://www.getambassador.io/user-guide/getting--启动 ）。
最后这个链接有问题

2018-09-12 12:22 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +如果您有兴趣将 Ambassador 用作 API 网关或 Kubernetes 入口解决方案，请查看[Ambassador入门指南]（https://www.getambassador.io/user-guide/getting--启动 ）。
Ingress不要翻译

2018-09-18 05:07 UTC, tengqm requested changes

2018-09-18 05:07 UTC, tengqm commented on content/cn/blog/_posts/2018-06-07-dynamic-ingress-kubernetes
> +如果您有兴趣将 Ambassador 用作 API 网关或 Kubernetes ingress 解决方案，请查看[Ambassador入门指南]（https://www.getambassador.io/user-guide/getting）。
I figured the original URL link is something like "https://www.getambassador.io/user-guide/getting-started". In your translation, the link now reports 404.

2018-09-23 12:09 UTC, markthink commented
@congfairy 文件有冲突，麻烦解决一下

2018-10-15 21:58 UTC, closed without merging