Congfairy patch 5
kubernetes/kubernetes-docs-zh pull request #537
Opened 2018-08-28 02:41 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-02 13:36 UTC, markthink commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +成为在全球范围有超过35,000人的社区时沟通是非常关键的。 跟踪Kubernetes社区中的所有内容可能是一项艰巨的任务。 一方面，我们有官方资源，如Stack Overflow，GitHub和邮件列表，另一方面，我们有更多实时的资源，如Slack，你可以在那里跳，与某人聊天，然后继续按你喜欢的方式去做。
中英文混排需要空格间隔

2018-09-02 13:36 UTC, markthink commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +While our current assortment of communication channels are valuable in their own rights, we found that there was still a gap between email and real time chat. Across the rest of the web, many other o
中英文间隔不宜过长

2018-09-02 13:37 UTC, markthink reviewed
总体都很棒，注意格式..

2018-09-12 12:42 UTC, tengqm requested changes

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +成为在全球范围有超过35,000人的社区时沟通是非常关键的。 跟踪 Kubernetes 社区中的所有内容可能是一项艰巨的任务。 一方面，我们有官方资源，如 Stack Overflow ，GitHub 和邮件列表，另一方面，我们有更多实时的资源，如 Slack，你可以在那里跳，与某人聊天，然后继续按你喜欢的方式去做。
when it comes to 不是  when it becomes ...

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +成为在全球范围有超过35,000人的社区时沟通是非常关键的。 跟踪 Kubernetes 社区中的所有内容可能是一项艰巨的任务。 一方面，我们有官方资源，如 Stack Overflow ，GitHub 和邮件列表，另一方面，我们有更多实时的资源，如 Slack，你可以在那里跳，与某人聊天，然后继续按你喜欢的方式去做。
ephemeral 是瞬时的

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +成为在全球范围有超过35,000人的社区时沟通是非常关键的。 跟踪 Kubernetes 社区中的所有内容可能是一项艰巨的任务。 一方面，我们有官方资源，如 Stack Overflow ，GitHub 和邮件列表，另一方面，我们有更多实时的资源，如 Slack，你可以在那里跳，与某人聊天，然后继续按你喜欢的方式去做。
where you can hop in 重翻

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +Slack非常适合随意和及时的对话，并与其他社区成员保持联系，但未来很难轻易引用通信。此外，在35,000名参与者中提问并得到回答很难。邮件列表在有问题尝试联系特定人群并且想要跟踪大家的回应时非常有用，但是对于大量人员来说可能是麻烦的。 Stack Overflow 和 GitHub 非常适合在涉及代码的项目或问题上进行协作，并且如果在将来要进行搜索也很有用，但某些主题如“你最喜欢的 CI /
CI / CD  -> CI/CD

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +虽然我们目前的各种沟通渠道对他们自己来说都很有价值，但我们发现电子邮件和实时聊天之间仍然存在差距。在网络的其他部分，许多其他开源项目，如 Docker ， Mozilla ，Swift ，Ghost 和 Chef ，已经成功地在[Discourse]（https://www.discourse.org/features ）之上构建社区，一个开放的讨论平台。那么，如果我们可以使用这个工具将我们的讨
> 对他们自己来说

就其自身而言

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +生态系统合作伙伴和开发人员现在有一个地方可以[宣布项目]（ https://discuss.kubernetes.io/c/announcements ），他们正在为用户工作，而不会想知道它是否会在官方列表中脱离主题。我们可以让这个地方不仅仅是关于核心Kubernetes，而是关于我们社区正在建设的数百个精彩工具。
> projects that they are working on
他们正在开发的项目

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +生态系统合作伙伴和开发人员现在有一个地方可以[宣布项目]（ https://discuss.kubernetes.io/c/announcements ），他们正在为用户工作，而不会想知道它是否会在官方列表中脱离主题。我们可以让这个地方不仅仅是关于核心Kubernetes，而是关于我们社区正在建设的数百个精彩工具。
> without wondering ....

不必担心 ....

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +生态系统合作伙伴和开发人员现在有一个地方可以[宣布项目]（ https://discuss.kubernetes.io/c/announcements ），他们正在为用户工作，而不会想知道它是否会在官方列表中脱离主题。我们可以让这个地方不仅仅是关于核心Kubernetes，而是关于我们社区正在建设的数百个精彩工具。
building -> 构造，开发

2018-09-12 12:42 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +进来看看。我们刚刚开始，所以您可能希望从[自我介绍]（https://discuss.kubernetes.io/t/introduce-yourself-here/56 ）开始，然后浏览。 [Android]（https://play.google.com/store/apps/details?id=com.discourse&hl=en_US&rdid=com.discourse&pli=1
最后一句乱了

2018-09-18 05:09 UTC, tengqm requested changes

2018-09-18 05:09 UTC, tengqm commented on content/cn/blog/_posts/2018-05-30-say-hello-to-discuss-kubernetes.md
> +进来看看。我们刚刚开始，所以您可能希望从[自我介绍]（https://discuss.kubernetes.io/t/introduce-yourself-here/56 ）开始，然后进行浏览。 [Android]（https://play.google.com/store/apps/details?id=com.discourse&hl=en_US&rdid=com.discourse&pli
Please check the links above. They may not work due to incorrect characters used.

2018-09-22 09:43 UTC, tengqm commented
need to check the link format and the conflict

2018-09-23 12:10 UTC, markthink commented
@congfairy 文件有冲突，麻烦解决一下。

2018-10-15 21:58 UTC, closed without merging