Congfairy patch 6
kubernetes/kubernetes-docs-zh pull request #538
Opened 2018-08-28 02:43 UTC by congfairy

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-02 13:37 UTC, markthink commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +2014年6月6日，我检查了Kubernetes公共代码库的第一次commit。许多人会认为这是故事开始的地方。这难道不是一切开始的地方吗？但这的确不能把整个过程说清楚。
中英文混排要有空格间隔

2018-09-02 13:37 UTC, markthink commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +The version of Kubernetes at that point was really just a shadow of what it was to become.  The core concepts were there but it was very raw.  For example, Pods were called Tasks.  That was changed a
中英文翻译对比内容不宜过长

2018-09-02 13:38 UTC, markthink reviewed
看你最近提交了很多，很赞，但需要注意一下提交格式..

2018-09-12 00:18 UTC, hanjiayao commented
@congfairy 两个建议 1）可以在您翻译文中检查一下，每一次出现的中文和英文单词之间，都需要增加一个空格。 比如 “我检查了Kubernetes公共代码库的第一次commit” 需要改成 “我检查了 Kubernetes 公共代码库的第一次 commit” 2）一小节英文 对应 一小节中文翻译（而不是三段英文之后翻译三段中文这样提交），这样便于我们大家进行 review

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +2014年6月6日，我检查了 Kubernetes 公共代码库的第一次 commit 。许多人会认为这是故事开始的地方。这难道不是一切开始的地方吗？但这的确不能把整个过程说清楚。
原文中的 checked in 在此处不宜翻译为“检查”，感觉用“检入”可能更合适点。

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +Kubernetes 建立在过去十年曾经在 Google 的 Borg 集群管理系统中验证过的思路之上。而 Borg 本身也是 Google 和其他公司早期努力的结果。
第一个句号是不是改为逗号？

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +具体而言，Kubernetes 最初是从 Brendan Burns 的一些原型开始，结合我和 Craig McLuckie 正在进行的工作，以更好地将 Google 内部实践与 Google Cloud 的经验相结合。 Brendan，Craig 和我真的希望人们使用它，所以我们建议将这个原型构建为一个开源项目，将Borg的最佳创意带给大家。
Borg前后的空格

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +在我们所有人同意后，就开始着手构建这个系统了。我们采用了 Brendan 的原型（Java语言），用Go语言重写了它，并且以上述核心思想去构建该系统。到这个时候，团队已经成长为包括 Ville Aikas，Tim Hockin，Brian Grant，Dawn Chen 和 Daniel Smith。一旦我们有了一些工作需求，有人必须承担一些脱敏的工作，以便为公开发布做好准备。这个角色最终由我承
“脱敏”的含义在上下文似乎不太明确

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +让我们一起期待下一个4年！
把撒花留下吧 :)

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +<!--
视频链接被注释掉了

2018-09-12 02:50 UTC, xiangpengzhao commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +![k8s_first_commit](/images/blog/2018-06-06-4-years-of-k8s/k8s-first-commit.png)
中文版的相对路径下并没有此图片，需要移过来。

2018-09-12 05:31 UTC, tengqm requested changes

2018-09-12 05:31 UTC, tengqm commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +在我们所有人同意后，就开始着手构建这个系统了。我们采用了 Brendan 的原型（Java语言），用Go语言重写了它，并且以上述核心思想去构建该系统。到这个时候，团队已经成长为包括 Ville Aikas，Tim Hockin，Brian Grant，Dawn Chen 和 Daniel Smith。一旦我们有了一些工作需求，有人必须承担一些脱敏的工作，以便为公开发布做好准备。这个角色最终由我承
had something working 不应翻译为 “有了一些工作需求”，英文原意是说有东西能运行了、可以工作了

2018-09-12 05:31 UTC, tengqm commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +在我们所有人同意后，就开始着手构建这个系统了。我们采用了 Brendan 的原型（Java语言），用Go语言重写了它，并且以上述核心思想去构建该系统。到这个时候，团队已经成长为包括 Ville Aikas，Tim Hockin，Brian Grant，Dawn Chen 和 Daniel Smith。一旦我们有了一些工作需求，有人必须承担一些脱敏的工作，以便为公开发布做好准备。这个角色最终由我承
check in 是提交代码的意思

2018-09-12 05:31 UTC, tengqm commented on content/cn/blog/_posts/2018-06-06-4-years-of-k8s.md
> +让我们一起期待下一个4年！
set of Kubernetes values 链接丢失

2018-09-18 05:10 UTC, tengqm commented
/lgtm

2018-09-23 12:10 UTC, markthink commented
@congfairy 文件有冲突，麻烦解决一下

2018-10-15 21:58 UTC, closed without merging