translate kube-scheduler.md
kubernetes/kubernetes-docs-zh pull request #540
Opened 2018-08-28 09:17 UTC by tianshapjq

translate kube-scheduler.md

2018-08-28 11:57 UTC, zhangxiaoyu-zidif commented
/lgtm

2018-08-29 02:49 UTC, tengqm requested changes

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +的资源要求、服务质量要求、硬件/软件/政策约束、亲和力和反亲和力规范、数据局部性、工作量间干扰，截止日期等。
> 工作量

负载

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +的资源要求、服务质量要求、硬件/软件/政策约束、亲和力和反亲和力规范、数据局部性、工作量间干扰，截止日期等。
> 截止日期

完成期限

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +      <td></td><td style="line-height: 130%; word-wrap: break-word;">弃用: 要使用的调度算法，其中之一：ClusterAutoscalerProvider |DefaultProvider</td>
> 其中之一：

可选值：

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +      <td></td><td style="line-height: 130%; word-wrap: break-word;">包含 Azure 容器注册表配置信息的文件的路径。</td>
此处 registry 最好翻译为“仓库”

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +    <td></td><td style="line-height: 130%; word-wrap: break-word;">弃用: 具有授权和 master 位置信息的 kubeconfig 文件的路径。</td>
> 具有

包含

2018-08-29 02:49 UTC, tengqm commented on content/cn/docs/reference/command-line-tools-reference/kube-scheduler.md
> +      <td></td><td style="line-height: 130%; word-wrap: break-word;">弃用: 具有调度器策略配置的文件。如果未提供策略 ConfigMap 或 --use-legacy-policy-config==true，则使用此文件</td>
> 具有

包含

2018-08-29 05:33 UTC, tengqm approved these changes
/lgtm

2018-08-29 06:12 UTC, Mr-Linus commented
I have signed the CNCF CLA. Why does this PR have no `CNCF-CLA:YES` label? @tengqm @zhangxiaoyu-zidif

2018-09-10 15:30 UTC, merged