tools.md tranlate
kubernetes/kubernetes-docs-zh pull request #551
Opened 2018-09-11 06:35 UTC by tianshapjq

tools.md tranlate

2018-09-11 13:46 UTC, pigletfly requested changes

2018-09-11 13:46 UTC, pigletfly commented on content/cn/docs/reference/tools.md
> +[`minikube`](/docs/tasks/tools/install-minikube/) ��һ��ߣ����Է����û����乤��վ�㱾�ز���һ��ڵ� Kubernetes ��Ⱥ�����ڿ����Ͳ���Ŀ�ġ�
`出于开发和测试目的` 这里语序看怎么调整下顺畅些

2018-09-11 23:59 UTC, hanjiayao commented on content/cn/docs/reference/tools.md
> +[`minikube`](/docs/tasks/tools/install-minikube/) ��һ��ߣ����Է����û����乤��վ�㱾�ز���һ��ڵ� Kubernetes ��Ⱥ�����ڿ����Ͳ���Ŀ�ġ�
[`minikube`](/docs/tasks/tools/install-minikube/) 是一个可以方便用户在其工作站点本地部署一个单节点 Kubernetes 集群的工具，用于开发和测试。

2018-09-12 01:45 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +[`minikube`](/docs/tasks/tools/install-minikube/) ��һ��ߣ����Է����û����乤��վ�㱾�ز���һ��ڵ� Kubernetes ��Ⱥ�����ڿ����Ͳ���Ŀ�ġ�
done

2018-09-12 01:46 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +[`minikube`](/docs/tasks/tools/install-minikube/) ��һ��ߣ����Է����û����乤��վ�㱾�ز���һ��ڵ� Kubernetes ��Ⱥ�����ڿ����Ͳ���Ŀ�ġ�
minikube 是一个可以方便用户在其工作站点本地部署一个单节点 Kubernetes 集群的工具，用于开发和测试。

2018-09-12 10:24 UTC, pigletfly commented
/lgtm

2018-09-13 02:02 UTC, tengqm requested changes

2018-09-13 02:02 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +title: Tools
Better translate the title

2018-09-13 02:02 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +[`Kubernetes Helm`](https://github.com/kubernetes/helm) ��һ�����Ԥ������ Kubernetes ��Դ��Ĺ��ߣ����� Kubernetes charts��
这里的 aka 对应的是 resources，请重新组织，避免误解

2018-09-13 02:02 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +*Ϊ Kubernetes Ӧ�ó��򴴽��ظ��Թ���
reproducible 是说可重现的

2018-09-13 02:02 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +*�Զ�������� Kubernetes �嵥�ļ�
intelligently 智慧地、明智地

2018-09-17 06:45 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +[`Kubernetes Helm`](https://github.com/kubernetes/helm) ��һ�����Ԥ������ Kubernetes ��Դ��Ĺ��ߣ����� Kubernetes charts��
Helm 是一个管理预先配置 Kubernetes 资源 或者可称之为 Kubernetes charts 的包管理工具，is better?

2018-09-17 06:53 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +*Ϊ Kubernetes Ӧ�ó��򴴽��ظ��Թ���
reproducible 我看了看原声权威例句，有重复不断的意思，"为 Kubernetes  应用提供可重复执行的构建",is ok?

2018-09-17 07:02 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +*�Զ�������� Kubernetes �嵥�ļ�
为您的 Kubernetes 清单文件提供更智能化的管理，is  better?

2018-09-18 05:13 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +[`Kubernetes Helm`](https://github.com/kubernetes/helm) ��һ�����Ԥ������ Kubernetes ��Դ��Ĺ��ߣ����� Kubernetes charts��
为了方便中文表达和断句，可以将一句话翻译成几句，符合汉语习惯。比如：

“Kubernetes Helm 是一个管理预先配置 Kubernetes 资源包的工具，这里的资源在 Helm 中也被称作 Kubernetes charts。

2018-09-18 05:14 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +*�Զ�������� Kubernetes �嵥�ļ�
agreed.

2018-09-18 05:14 UTC, tengqm commented on content/cn/docs/reference/tools.md
> +*Ϊ Kubernetes Ӧ�ó��򴴽��ظ��Թ���
“可重复执行的” okay

2018-09-18 06:56 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +title: Tools
done

2018-09-18 06:56 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +[`Kubernetes Helm`](https://github.com/kubernetes/helm) ��һ�����Ԥ������ Kubernetes ��Դ��Ĺ��ߣ����� Kubernetes charts��
done

2018-09-18 06:56 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +*Ϊ Kubernetes Ӧ�ó��򴴽��ظ��Թ���
done

2018-09-18 06:56 UTC, tianshapjq commented on content/cn/docs/reference/tools.md
> +*�Զ�������� Kubernetes �嵥�ļ�
done

2018-09-18 08:04 UTC, tengqm commented
/lgtm

2018-09-23 12:11 UTC, merged