translate docs/tutorials/kubernetes-basics/scale/scale-intro.html
kubernetes/kubernetes-docs-zh pull request #558
Opened 2018-09-15 15:52 UTC by chenrui333

2018-09-17 07:18 UTC, hanjiayao commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +title: 运行多个应用程序实例
运行应用的多个实例

2018-09-17 07:23 UTC, hanjiayao commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +
Deployment 仅为跑这个应用程序创建了一个 Pod。当流量增加时，我们需要扩容应用程序来满足用户需求。

2018-09-17 11:23 UTC, chenrui333 commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +title: 运行多个应用程序实例
感觉这两种意思都差不多？

2018-09-17 11:24 UTC, chenrui333 commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +
👍

2018-09-18 13:00 UTC, chenrui333 commented
@hanjiayao I have adopted your suggestions, please re-check on the PR, thanks!

2018-09-19 01:00 UTC, pigletfly requested changes

2018-09-19 01:00 UTC, pigletfly commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +										<li>用 kubectl 扩缩应用程序</li>
scale 是不是在 k8s 里一般翻译为伸缩容？

2018-09-19 01:00 UTC, pigletfly commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +								<p>扩展 Deployment 将创建新的 Pods，并将资源调度请求分配到有可用资源的节点上，收缩 会将 Pods 数量减少至所需的状态。Kubernetes 还支持 Pods 的<a href="http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/">自动缩放</a>，但这并不在本教程的讨论范围内。
注意空格

2018-09-19 14:14 UTC, chenrui333 commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +										<li>用 kubectl 扩缩应用程序</li>
`伸缩容` 感觉都不是一个词？我看有些翻译用的就是伸缩

2018-09-19 14:16 UTC, chenrui333 commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +								<p>扩展 Deployment 将创建新的 Pods，并将资源调度请求分配到有可用资源的节点上，收缩 会将 Pods 数量减少至所需的状态。Kubernetes 还支持 Pods 的<a href="http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/">自动缩放</a>，但这并不在本教程的讨论范围内。
Thanks!

2018-09-20 04:10 UTC, chenrui333 commented
/check-cla

2018-09-20 05:24 UTC, hanjiayao commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +										<li>用 kubectl 扩缩应用程序</li>
扩容/缩容/扩缩容（具体取决于文章细节的context）

2018-09-20 12:49 UTC, chenrui333 commented on content/cn/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +										<li>用 kubectl 扩缩应用程序</li>
`扩缩容` 感觉有点绕口啊

2018-09-23 12:13 UTC, merged