translate kubeadm-upgrade-1-11.md
kubernetes/kubernetes-docs-zh pull request #559
Opened 2018-09-17 03:01 UTC by chentao1596

>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> For 1.12 Features: set Milestone to 1.12 and Base Branch to release-1.12
>^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
> Please delete this note before submitting the pull request.

2018-09-20 14:39 UTC, pigletfly requested changes

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +title: 将kubeadm集群从 v1.10 版本更新到 v1.11 版本
注意中英文间的空格,下面的也有些要注意

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +This page explains how to upgrade a Kubernetes cluster created with `kubeadm` from version 1.10.x to version 1.11.x, and from version 1.11.x to 1.11.y, where `y > x`.
本文介绍如何升级通过 `kubeadm` 创建的 Kubernetes 集群

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +### 此外
附加信息？更多信息？

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 您可以仅从一个小版本升级到下一个小版本。也就是说，当您升级的时候，您不能跨域版本来进行升级。比如您只能从 1.10 版本升级到 1.11 版本，不能直接从 1.9 版本升级到 1.11 版本。
跨越

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +    请注意在您的系统升级控制平面之前升级的 `kubeadm` 包会造成升级失败。尽管 `kubeadm` ships 存储在 Kubernetes 仓库中，但是手动升级它是重要的。kubeadm 团队在努力解决这个限制。
ships 这里应该翻译为发布？

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 准备对于每个主机维护，标记为不可达和收回工作负载：
不可调度和驱逐工作负载？

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 通过标记可计划将主机重新连接：
通过标记为可调度将主机重新上线

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 应用新的“kube-dns”和“kube-proxy”清单并强制创建所必须的RBAC规则
标点不对，应该为 `

2018-09-20 14:39 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +  -API服务器是否可达
检查下 markdown 语法

2018-09-29 02:07 UTC, zhangxiaoyu-zidif commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 您可以仅从一个小版本升级到下一个小版本。也就是说，当您升级的时候，您不能跨域版本来进行升级。比如您只能从 1.10 版本升级到 1.11 版本，不能直接从 1.9 版本升级到 1.11 版本。
s/跨域/跨越

2018-09-29 02:15 UTC, zhangxiaoyu-zidif commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +    请注意在您的系统升级控制平面之前升级的 `kubeadm` 包会造成升级失败。尽管 `kubeadm` ships 存储在 Kubernetes 仓库中，但是手动升级它是重要的。kubeadm 团队在努力解决这个限制。
ships 在这里不是 发布也不是存储，更像是 内嵌在，包含于的意思。

2018-09-29 02:15 UTC, zhangxiaoyu-zidif commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 在每个 node 上除了 master node，升级 kubelet 配置：
在master节点外的其他node上

2018-09-29 02:15 UTC, zhangxiaoyu-zidif commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 重新启动 kubectl 过程：
过程-> 进程

2018-10-13 08:36 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 您需要先安装一个版本为 1.10.0 或更高版本的 `kubeadm` Kubernetes 集群。另外还需要禁用节点的交换分区。该集群需要使用一个静态的控制面板和 etcd pods。
对于技术文档, “你”会不会更合适一点?

2018-10-13 08:36 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 确保备份任何重要的组件，例如存储在数据库中的 app-level 状态。`kubeadm upgrade`不涉及到您的工作负载，只涉及kubernetes内部组件，但是备份始终是最好的方案。
> 确保备份好所有重要的组件, 例如存储在数据库当中的应用级别的状态信息
> `kubeadm upgrade` 不会影响到你的应用层业务负载, 只会涉及到 Kubernetes 的内部组件, 但是提前备份始终是最好的方案.

2018-10-13 08:36 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 在升级之后所有的容器要重新启动，因为容器规范的哈希值改变了。
> 所有的容器在升级完成之后都重启了一次，因为容器的 spec 哈希值改变了。

spec 是不是可以作为一个通用技术术语而不翻译? 翻译成“规范”感觉会有歧义.

2018-10-13 08:36 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +- 您可以仅从一个小版本升级到下一个小版本。也就是说，当您升级的时候，您不能跨域版本来进行升级。比如您只能从 1.10 版本升级到 1.11 版本，不能直接从 1.9 版本升级到 1.11 版本。
> 你只能从一个小版本升级到下一个小版本。也就是说，你不能跨版本升级。例如，你可以从 1.10 版本升级到 1.11 版本，但是不能从 1.9 版本升级到 1.11 版本。

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +为了保留 `kube-dns`，请传入 `--feature-gates=CoreDNS=false` 参数到 `kubeadm upgrade apply`。
> 如果要使用 `kube-dns` ，在执行 `kubeadm upgrade apply` 时加上参数 `--feature-gates=CoreDNS=false` 即可。

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 在您的 master 节点上，以 root 用户运行以下步骤：
> 在你的 master 节点上, 以 root 用户执行以下步骤：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +    请注意在您的系统升级控制平面之前升级的 `kubeadm` 包会造成升级失败。尽管 `kubeadm` ships 存储在 Kubernetes 仓库中，但是手动升级它是重要的。kubeadm 团队在努力解决这个限制。
> 虽然 `kubeadm` 已经包含在 Kubernetes 仓库当中了，但手动安装 `kubeadm` 仍然是不可或缺的一步。

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1.  确认 kubeadm 下载工作和达到预期的版本：
> 1.  确保可以下载并且下载到的是想要的版本：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 在master节点上运行：
> 1. 在 master 节点上执行以下命令：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +  运行之后，可以看到类似下面的输出：
> 执行完命令之后，你应该可以看到类似于下面这样的输出：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +   在 v1.10 版本系列中升级到最新的版本：
> 升级到 v1.10 系列的最新版本：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +   现在您可以通过执行以下命令来进行升级：
“你”

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +   注意：在您执行升级之前，必须升级 kubeadm 到 v1.11.0 版本。
> 注意：在执行此次升级之前，必须确保 kubeadm 已经升级到了 v1.11.0 版本。

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +    下面命令查看你的集群升级和获取您的集群所升级到的版本。
> 这条命令会检查你的集群是否可以升级, 并拉取你能升级的版本。

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +1. 选择一个版本来进行升级和运行正确的命令。例如：
> 1. 选择一个要升级的版本并运行恰当的命令。例如：

2018-10-14 15:56 UTC, yelongyu commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-1-11.md
> +    如果您最近使用  `kube-dns` 和继续想这样使用的话，请添加 `--feature-gates=CoreDNS=false` 参数。
> 如果你现在正在使用 `kube-dns` 并且希望继续使用，记得加上参数 `--feature-gates=CoreDNS=false` 。
> 你应该能够看到类似如下的输出：

2018-10-15 12:14 UTC, chentao1596 commented
@pigletfly @zhangxiaoyu-zidif @yelongyu @xiangpengzhao @markthink 由于合入错误太多，不好回滚，重新提交了，麻烦几位重新帮忙看下，谢谢！！
https://github.com/kubernetes/kubernetes-docs-zh/pull/577

2018-10-15 12:14 UTC, closed without merging