translate and update kubeadm-upgrade-ha.md
kubernetes/kubernetes-docs-zh pull request #560
Opened 2018-09-18 08:36 UTC by chentao1596

2018-09-23 12:04 UTC, markthink commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
> +>
这里注解有问题，需修复

2018-09-25 01:08 UTC, pigletfly requested changes

2018-09-25 01:08 UTC, pigletfly commented on content/cn/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade-ha.md
> +title: 升级kubeadm HA集群从 1.9.x 版本到 1.9.y 版本
注意空格，下面一样

2018-10-15 12:28 UTC, chentao1596 commented
@pigletfly @markthink updated, please take a look again, thank you!

2018-10-15 21:58 UTC, closed without merging