list-all-running-contianer-image-pr-2017-12-04
kubernetes/kubernetes-docs-zh pull request #65
Opened 2017-12-04 01:14 UTC by zhangqx2010

2017-12-04 01:46 UTC, chentao1596 reviewed
翻译内容没有问题，不过，根据 版本控制的样例说明，我觉得应该同时把“list-all-running-container-images-2017-8-15.md”这个文件给删除，并且更新list-all-running-container-images.md，请参考：https://github.com/kubernetes/kubernetes-docs-cn#三版本控制与翻译文件更新样例

2017-12-05 06:57 UTC, pigletfly requested changes

2017-12-05 06:57 UTC, pigletfly commented on docs/tasks/access-application-cluster/list-all-running-container-images.md
> +本文说明如何使用 kubectl 查看所有集群中运行的 Pod 所使用的 Container Image。
应该是一个集群吧

2017-12-05 06:57 UTC, pigletfly commented on docs/tasks/access-application-cluster/list-all-running-container-images.md
> +这个练习中将使用 kubectl 获取集群中所有的 Pod，并且格式化地输出每个 Pod 包含的 Container。
一个集群中运行的全部 Pod ?

2017-12-05 07:31 UTC, zhangqx2010 commented on docs/tasks/access-application-cluster/list-all-running-container-images.md
> +本文说明如何使用 kubectl 查看所有集群中运行的 Pod 所使用的 Container Image。
集群中所有运行的 Pod
语序要调整下

2017-12-05 07:36 UTC, zhangqx2010 commented on docs/tasks/access-application-cluster/list-all-running-container-images.md
> +本文说明如何使用 kubectl 查看所有集群中运行的 Pod 所使用的 Container Image。
应该是运行于集群中的所有 Pod，下面也一样，如果没有 pod 是非 running 也会显示，这里的running应该不是强调在 running 状态的 pod

2017-12-07 01:10 UTC, merged