extend-api-third-party-resource-pr-2017-12-04
kubernetes/kubernetes-docs-zh pull request #72
Opened 2017-12-04 08:17 UTC by zhangqx2010

2017-12-04 08:54 UTC, lichuqiang requested changes

2017-12-04 08:54 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +**ThirdPartyResource 在 Kubernetes 1.7 中被降级。它在 1.8 版本中已经依据 [降级策略](/docs/reference/deprecation-policy) 移除。
deprecated 弃用

2017-12-04 08:54 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +Kubernetes 有许多与生俱来的内置 API 对象。然而，在很多需要自定义自动化的场景中，需要使用您自己的 API 对象扩展 Kubernetes。
“与生俱来”似乎没必要？
在很多需要自定义自动化的场景中 ——> 为实现自定义自动化，很多时候XXX

2017-12-04 08:54 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +`ThirdPartyResource` 的 `kind` 取自于 `<kind name>.<domain>`。您必须提供一个唯一的 kind 和 domain 名来防止与其他 `ThirdPartyResource` 对象冲突。当创建 `ThirdPartyResource` 实例时，Kind 名会被转换为 CamelCase 类型。`kind` 内的连字符用于断词，比如， `camel-c
“Kind 名会被转换为 CamelCase 类型“，这里的 CamelCase（驼峰命名法）翻译一下更好。

2017-12-04 08:54 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +在如下例子中，`cronSpec` 和 `image` 字段被设置到了名为 `CronTab` 的自定义对象中。`CronTab` 是引用了我们刚刚创建的 `ThirdPartyResource` 对象的 `metadata.name`。
`CronTab` 是引用了
“是”多余，`CronTab` 取自

2017-12-04 09:28 UTC, zhangqx2010 commented
updated

2017-12-04 09:39 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +`ThirdPartyResource` 的 `kind` 取自于 `<kind name>.<domain>`。您必须提供一个唯一的 kind 和 domain 名来防止与其他 `ThirdPartyResource` 对象冲突。当创建 `ThirdPartyResource` 实例时，Kind 名会被转换为驼峰命名法（CamelCase）类型。`kind` 内的连字符用于断词，比如， `ca
emm，”Kind 名会被转换为驼峰命名法（CamelCase）类型“ 这里最好灵活处理一下：
“Kind 名称会按照驼峰命名法（CamelCase）进行转换”

2017-12-04 09:39 UTC, lichuqiang commented on docs/tasks/access-kubernetes-api/extend-api-third-party-resource.md
> +这个端点 URL 就能用于创建和管理自定义对象。依据 `ThirdPartyResource`(`cron-tab.stable.example.com`) 的 `metadata.name` 的驼峰命名法规则，这个对象的 `kind` 值就是 `CronTab`。
“applied to”漏掉了，直译的话显得有些啰嗦，建议用括号处理一下，另外“these objects”为复数：
依据驼峰命名规则（应用于 `ThirdPartyResource`(`cron-tab.stable.example.com`) 的 `metadata.name` 字段），这些对象的 `kind` 值为 `CronTab`。

2017-12-04 12:44 UTC, lichuqiang approved these changes

2017-12-05 06:30 UTC, lichuqiang commented
@zhangqx2010 Could you merge the git commit records?

2017-12-07 01:59 UTC, merged