example-task-template-pr-2017-12-04
kubernetes/kubernetes-docs-zh pull request #73
Opened 2017-12-04 09:22 UTC by zhangqx2010

@markthink 这个很短，但是模板文件，你亲自review一下吧。

2017-12-05 07:08 UTC, pigletfly requested changes

2017-12-05 07:08 UTC, pigletfly commented on docs/tasks/example-task-template.md
> +## 如何…
这里好像少了一段

2017-12-05 07:37 UTC, zhangqx2010 commented on docs/tasks/example-task-template.md
> +## 如何…
漏了 慢点加一下

2017-12-07 01:38 UTC, lichuqiang commented on docs/tasks/example-task-template.md
>  title: Example Task Template
标题也需要翻译

2017-12-07 01:38 UTC, lichuqiang commented on docs/tasks/example-task-template.md
> +这里是有意思的东西，关于你具体实现的步骤。
to know about没有翻译出来

2017-12-10 05:57 UTC, markthink commented
@zhangqx2010  OK

2017-12-10 05:58 UTC, merged