web-ui-dashboard-pr-2017-12-05
kubernetes/kubernetes-docs-zh pull request #78
Opened 2017-12-05 13:41 UTC by zhangqx2010

2017-12-06 00:52 UTC, chentao1596 commented
@zhangqx2010 请问这个文档时计划分成两次来完成翻译的吗？因为我只看到了上面一个部分，后面没有翻译。根据我的理解，这个文章不长，不应该需要两次才对，请确定，谢谢！^_^

2017-12-06 01:53 UTC, zhangqx2010 commented
咦？昨天翻译完了，没完全提交上来，晚上弄一下

2017-12-06 12:47 UTC, zhangqx2010 commented
完整翻译已提交

2017-12-07 04:54 UTC, chentao1596 reviewed
我先看了一部分，有些地方我觉得翻译可能不准确，也有些是我觉得可能换个方式更好的，请酌情修改，后面再提交剩下部分的Review，谢谢！

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Dashboard 是 Kubernetes 基于 web 的用户界面。你可以使用 Dashboard 部署容器应用，对容器应用排错，并且管理集群及其资源。可以使用 Dashboard 概览集群中的应用，也可以创建或调整 Kubernetes 资源（如 Deployment，Job，DaemonSet 等等）。例如，你可以扩展 Deployment，创建滚动升级，重启 Pod 或者使用向导创建新
有些地方，我觉得可以做些小的调整，下面是我理解翻译的内容，请酌情参考：
Dashboard 是基于 web 的 Kubernetes 用户界面。使用 Dashboard，您可以将容器化应用部署到 Kubernetes 集群中，也可以对容器化应用排错，还能管理集群本身及其附属资源。您可以使用 Dashboard 获取运行在集群中的应用的概览信息，也可以创建或者修改 Kubernetes（如 Deployment，Job，DaemonSet 等等）资源。例如，您可以对 Deployment 实现弹性伸缩、创建滚动升级、重启 Pod 或者使用向导创建新的应用。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Dashboard 同时提供 Kubernetes 集群中的资源状态信息和所有报错信息。
提供
->
展示了
Dashboard上有资源信息和报错信息的展示，所以，原文虽然是提供的意思，但是，我建议这里用 展示 更贴切

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Dashboard 默认不会部署。可以使用如下命令进行部署：
默认情况下，没有部署 Dashboard。如果想要部署它，请运行如下命令：

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +访问 Dashboard UI 有很多途径；可以使用 kubectl 命令行接口，或者使用浏览器访问 Kubernetes master apiserver。
途径
->
方式
个人感觉方式在这里更好

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +你可以使用 kubectl 命令行工具访问 Dashboard，命令如下：
建议文章中的“你”都换成"您"

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Kubectl 会处理与 apiserver 的认证过程，并提供 Dashboard 的访问路径 http://localhost:8001/ui。
并提供 Dashboard 的访问路径 http://localhost:8001/ui。
->
并使得 Dashboard  能够通过 http://localhost:8001/ui 访问。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +UI 可以直接通过 Kubernetes master apiserver 访问。打开浏览器输入 `https://<kubernetes-master>/ui`，其中 `<kubernetes-master>` 是 Kubernetes master 的 IP 地址或者域名。
打开浏览器输入
->
打开浏览器，输入

建议在这里断句，读起来感觉更好

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +请注意，只有当 apiserver 允许使用用户名密码方式认证时，这种方式才可以正常工作。但对于安装工具（如 `kubeadm`）来说并非如此。关于如何手工设置认证，参见 [authentication 管理文档](/docs/admin/authentication/)。
只有当 apiserver 设置为允许使用用户名和密码进行认证，这种方式才可以正常工作

这里前后有两个"方式"，读起来比较拗口，所以，建议去掉一个

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +请注意，只有当 apiserver 允许使用用户名密码方式认证时，这种方式才可以正常工作。但对于安装工具（如 `kubeadm`）来说并非如此。关于如何手工设置认证，参见 [authentication 管理文档](/docs/admin/authentication/)。
但对于安装工具（如 `kubeadm`）来说并非如此
->
当前有些安装工具（如 `kubeadm`）并没有这样设置。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +当访问空集群的 Dashboard 时，你会看到欢迎界面。这个页面会包含到本文的链接，同时有一个按钮用于部署您的第一个应用。此外，你可以看到在默认情况下有哪些系统应用运行在 `kube-system` [namespace](/docs/tasks/administer-cluster/namespaces/) 中，比如 Dashboard 自己。
这个页面会包含到本文的链接，同时有一个按钮用于部署您的第一个应用
->
页面包含一个指向此文档的链接，以及一个用于部署第一个应用程序的按钮。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Dashboard 能让你通过一个简单的向导，创建和部署容器成为一个 Deployment 和可选的 Service。可以手工指定应用的详细配置，或者上传一个包含应用配置的 YAML 或 JSON 文件。
通过一个简单的向导，您可以使用 Dashboard 将容器化应用作为一个 Deployment 和可选的 Service  进行创建和部署。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +### 定制应用的详细配置
定制
->
指定

这里我感觉还是用指定比较好，我理解一般定制是向别人要求，指定是自己去做，这里我倾向于是自己去做

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +  应用名称必须在选定的 Kuberntes [namespace](/docs/tasks/administer-cluster/namespaces/) 中唯一存在。必须由小写字母开头，以数字或者小写字母结尾，并且只含有小写字母、数字和中划线（-）。小于等于24个字符。开头和结尾的空格会被忽略。
应用名称必须在选定的 Kuberntes [namespace](/docs/tasks/administer-cluster/namespaces/) 中唯一存在。
->
在选定的 Kuberntes [namespace](/docs/tasks/administer-cluster/namespaces/) 中，要求应用名称唯一。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Number of pods**（必填）：部署应用 Pod 的目标数量。值必须为整型。
部署应用 Pod 的目标数量。值必须为整型。
->
您希望应用程序部署的 Pod 的数量。值必须为正整数。

这里应该是正整数

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Service**（可选）：对于应用的某些部分（比如前端），您可能想对外暴露 [Service](/docs/concepts/services-networking/service/) ，可能是集群外部（外部服务）的公网地址。对于外部服务，需要开放一个或者多个端口来满足。更多信息请参考 [这里](/docs/tasks/access-application-cluster/config
这里的(external Service)里面的Servcie是大写，我理解应该是 K8s 里面的Service的概念，所以我觉得这里不应该翻译

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +  其他只能对集群内部可见对 Service 称为 internal Service。
其他
->
其它

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +  与 Service 类型无关，如果您选择创建一个 Service，容器监听一个（入向的）端口，那么您需要定义两个端口。创建的 Service 会将（入向的）端口映射到容器可见的目标端口。这个 Service 会为部署的 Pod 路由。支持 TCP 和 UDP 协议。这个 Service 内部的 DNS 解析名就是之前你定义的应用名称。
不管哪种 Service 类型，如果您选择创建一个 Service，而且容器在一个端口上开启了监听（入向的）...

这个 Service 会为部署的 Pod 路由。->Service 将会路由到您部署的 Pod。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +如果需要，您可以扩展 **高级选项** 部分，这里您可以定义更多设置：
扩展
->
打开

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Description**：这里你输入的文本会为 Deployment 添加一个 [annotation](/docs/concepts/overview/working-with-objects/annotations/)，会显示在应用的详细信息中。
您在此输入的文本将作为一个 [annotation](/docs/concepts/overview/working-with-objects/annotations/) 添加到 Deployment，并显示在应用的详细信息中。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Labels**：默认用于应用的 [labels](/docs/concepts/overview/working-with-objects/labels/) 是应用名称和版本。您可以为 Deployment、Service（如果有）定义额外的 label，比如 release、environment、tier、partition 和 release track。
应用默认使用的 [labels](/docs/concepts/overview/working-with-objects/labels/) 是应用名称和版本

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Namespace**：Kubernetes 支持多个虚拟集群依附于同一个物理集群。这些虚拟集群被称为 [namespaces](/docs/tasks/administer-cluster/namespaces/)。他们能够让你将资源分派到逻辑的命名组中。
他们能够让你将资源分派到逻辑的命名组中。
->
它们让您将资源划分为逻辑命名的组。

1）这里应该是“它们”，不是“他们”
2）我觉得这里应该是强调将资源分组，所以，划分应该更好

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Image Pull Secret**：在 Docker 容器镜像是私有的情况下，会需要 [pull secret](/docs/concepts/configuration/secret/) 凭证。
想要使用私有的 Docker 容器镜像，需要....

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +  Dashboard 通过下拉菜单提供所有可用的 secret，并允许你创建新的 secret。secret 名称必须遵循 DNS 域名语法，比如 new.image-pull.secret`。secret 的内容必须是 base64 编码的，并且在一个 [`.dockercfg`](/docs/concepts/containers/images/#specifying-imagepulls
new.image-pull.secret\`
->
\`new.image-pull.secret\`

丢掉了前面的符号 \`

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +  在 image pull secret 创建成功的情况下，默认会选中新的 secret 会。如果创建失败，则不会应用任何 secret。
默认会选中新的 secret 会
->
默认会选中新的 secret

后面那个“会”是多余的

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Run command** and **Run command arguments**: By default, your containers run the specified Docker image's default [entrypoint command(/docs/user-guide/containers/#containers-and-commands). You ca
这里copy上面一行出现了错误，“ [entrypoint command”后面的“]”丢掉了
如果以后的文档需要同时保留中英文的话，这里可能会有误解，建议应该保持原文

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +- **Run as privileged**：这个设置决定了在 [特权容器](/docs/user-guide/pods/#privileged-mode-for-pod-containers) 中运行的进程是否像主机中使用 root 运行的进程一样。特权容器有能力操作网络堆栈或者访问设备。
特权容器可以使用诸如操纵网络堆栈和访问设备的功能。

这里我理解，应该不止这两项功能，这两个功能只是举例，所以，我觉得加上“诸如”这个词更好

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Kubernetes 支持声明式配置。这种风格中，所有的配置都是存储在 YAML 或者 JSON 配置文件中，使用 Kubernetes [API](/docs/concepts/overview/kubernetes-api/) 资源 schema。
所有的配置都是存储在 YAML 或者 JSON 配置文件中，使用 Kubernetes [API](/docs/concepts/overview/kubernetes-api/) 资源 schema。
->
所有的配置都存储在遵循 Kubernetes [API](/docs/concepts/overview/kubernetes-api/) 资源 schema 的 YAML 或者 JSON 配置文件中。

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +或者，可以通过部署向导定义应用的详情，您可以在 YAML 或者 JSON 文件中定义应用，并且使用 Dashboard 上传文件：
作为一种替代在部署向导中指定应用详情的方式，您可以......

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
>  Dashboard shows most Kubernetes object kinds and groups them in a few menu categories.
line 264: 这行没有看到翻译，是漏掉了么？

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +集群和 namespace 管理的视图。它会列出 Nodes、Namespaces 和 Persistent Volumes，并且有它们的详细视图。节点列表视图包含从所有节点聚合的 CPU 和内存使用的度量值。详细信息视图显示了一个节点的度量值，它的定义、状态、分配的资源、事件和这个节点上运行的 Pod。
这里的Node应该都是指K8s系统中的Slave，所以，这里不应该翻译

its specification
->
我觉得这个说规格比说定义要好

2017-12-07 04:54 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Entry point 视图显示选中 namespace 中所有运行的应用。视图按照负载类型（如 Deployment、Replica Set、Stateful Set 等）罗列应用，并且每种负载都可以单独查看。列表总结了关于负载的可执行信息，比如一个 Replica Set 的 ready 状态的 Pod 数量，或者目前一个 Pod 的内存使用量。
这里的Entry point建议还是需要翻译

2017-12-08 09:30 UTC, chentao1596 requested changes
Review完成，谢谢！ ^_^

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +服务和发现视图展示允许暴露给外网服务和允许集群内部发现的 Kubernete 资源。因此，Service 和 Ingress 视图展示他们关联的资源，给集群连接使用的内部端点和给外部用户使用的外部端点。
Kubernete 资源
->
Kubernetes 资源

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +服务和发现视图展示允许暴露给外网服务和允许集群内部发现的 Kubernete 资源。因此，Service 和 Ingress 视图展示他们关联的资源，给集群连接使用的内部端点和给外部用户使用的外部端点。
Service 和 Ingress 视图展示他们关联的资源，给集群连接使用的内部端点和给外部用户使用的外部端点。
->
Service 和 Ingress 视图展示他们关联的 Pod、给集群连接使用的内部端点和给外部用户使用的外部端点。

这里应该的“资源”，我觉得还是原文说的 Pod 比较对，属于目标 Pod

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +存储视图展示 PVC 资源（Persistent Volume Claim），这些资源被用于存储应用数据。
这些资源被用于存储应用数据。
->
这些资源被用于存储数据的应用程序使用。

这里应该是说资源被应用程序使用，这些应用程序用于存储数据，不是说存储这些应用数据

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。目前来说就是 Config Map 和 Secret。通过这个视图可以编辑和管理 config 对象，而 secret 的内容默认是隐藏显示的。
配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。
->
配置视图展示的所有 Kubernetes 资源是在集群中运行的应用程序的实时配置。

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。目前来说就是 Config Map 和 Secret。通过这个视图可以编辑和管理 config 对象，而 secret 的内容默认是隐藏显示的。
而 secret 的内容默认是隐藏显示的。
->
并显示那些默认隐藏的 secret。

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Pod 列表和详细信息页面会链接到 Dashboard 内置的日志查看器。查看器可以钻取同一个 Pod 中容器的日志。
钻取
->
获取

这里跟我的理解，应该是把所有容器的日志都能拿过来，并且展示，所有，我建议翻译成为获取就行了

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +Pod 列表和详细信息页面会链接到 Dashboard 内置的日志查看器。查看器可以钻取同一个 Pod 中容器的日志。
会
->
可以

我建议改成可以，应该是可以通过链接访问进去，而不是自动跳转

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +负载的详细视图展示状态、详细信息和对象间的关系。例如，Pod 收什么 Replica Set 控制，或者 Deployment 的新建 Replica Set 和 Horizontal Pod Autoscaler。
例如，Pod 收什么 Replica Set 控制，或者 Deployment 的新建 Replica Set 和 Horizontal Pod Autoscaler。
->
例如，Replica Set 所控制的 Pod，或者 Deployments 关联的 New Replica Set 和 Horizontal Pod Autoscaler。

感觉这样子描述更加的好

2017-12-08 09:30 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +参照描述 Kubernetes Dashboard UI 视图的章节；其中定义了提供的功能以及如何使用这些功能。
以下各节描述了 Kubernetes Dashboard UI 视图；包括它们提供的内容，以及怎么使用它们。

2017-12-08 13:32 UTC, zhangqx2010 commented
细致，点赞

2017-12-08 14:21 UTC, zhangqx2010 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +负载的详细视图展示状态、详细信息和对象间的关系。例如，Pod 收什么 Replica Set 控制，或者 Deployment 的新建 Replica Set 和 Horizontal Pod Autoscaler。
这里本来想翻译成你说的 ”Replica Set 所控制的 Pod“
但是上下文看是应该强调两者的控制关系，所以当时没想到更好的翻法

2017-12-08 14:24 UTC, zhangqx2010 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。目前来说就是 Config Map 和 Secret。通过这个视图可以编辑和管理 config 对象，而 secret 的内容默认是隐藏显示的。
这里应该是指 secret是以密文显示？

2017-12-08 14:27 UTC, zhangqx2010 commented
已经完成更新 除了一处需要确认

而 secret 的内容默认是隐藏显示的。
->
并显示那些默认隐藏的 secret。

2017-12-10 05:55 UTC, markthink commented
@zhangqx2010 已经可以了么？可以 merge 时，@我..

2017-12-11 00:29 UTC, chentao1596 commented
@markthink @zhangqx2010 这次的内容比较多，上次review的时候花了一整天，我再看看吧，等确定了再@，谢谢！！

2017-12-11 11:50 UTC, chentao1596 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。目前来说就是 Config Map 和 Secret。通过这个视图可以编辑和管理 config 对象，而 secret 的内容默认是隐藏显示的。
我装了dashboard看了下，secret的内容并不会显示，所以，这里确实应该是“内容是隐藏的”，只显示了内容的大小

所以，我觉得这里应该是说，”通过这个试图可以编辑和管理 config 对象 和 展示那些默认隐藏内容的 secret“

下面是我获取到的一个内容：

···
Details
Name:
default-token-1mlrt
Namespace:
default
Annotations:
kubernetes.io/service-account.name: default
kubernetes.io/service-account.uid: 92a654c3-de22-11e7-b1f5-0019c69adad6
Creation time:
2017-12-11T03:22
Data
 
remove_red_eye
 ca.crt:
1346 bytes

remove_red_eye
 namespace:
7 bytes

remove_red_eye
 token:
846 bytes
···

2017-12-11 11:51 UTC, chentao1596 commented
@zhangqx2010 我看到的内容好像还是之前的，是否确定内容已经更新？谢谢

2017-12-12 01:05 UTC, zhangqx2010 commented on docs/tasks/access-application-cluster/web-ui-dashboard.md
> +配置视图展示所有 Kubernetes 资源，这些资源是运行于集群中的应用的在线配置。目前来说就是 Config Map 和 Secret。通过这个视图可以编辑和管理 config 对象，而 secret 的内容默认是隐藏显示的。
ok

2017-12-12 01:07 UTC, zhangqx2010 commented
@chentao1596 我检查了下应该已经都修改完成了，你再看一下？

2017-12-14 08:41 UTC, zhangqx2010 commented
@markthink 看下没问题的话merge一下吧

2017-12-17 07:22 UTC, merged