getting-started-guides-ubuntu-storage-2017-12-06
kubernetes/kubernetes-docs-zh pull request #81
Opened 2017-12-06 08:50 UTC by Tony-CCIE

2017-12-06 09:04 UTC, pigletfly requested changes

2017-12-06 09:04 UTC, pigletfly commented on docs/getting-started-guides/ubuntu/storage.md
> +这个事例中创建了50 MB 大小的 “test" Rados 块设备 (rbd)。
示例或者例子？

2017-12-06 09:04 UTC, pigletfly commented on docs/getting-started-guides/ubuntu/storage.md
> +在您 Kubernetes 集群上使用 watch 命令，如下所示，您应该看到 PV 已经标记为可用：
在您的

2017-12-06 09:04 UTC, pigletfly commented on docs/getting-started-guides/ubuntu/storage.md
> +Kubernetes 的正则分布，和您的持久化存储设备相关，例如 [Ceph](http://ceph.com)。配合 [Juju Storage](https://jujucharms.com/docs/2.0/charms-storage)功能可轻松跨越云端添加持久化存储。
Kubernetes 标准的分布性允许你连接到持久化存储设备？

2017-12-06 09:35 UTC, linyouchong reviewed
供参考

2017-12-06 09:35 UTC, linyouchong commented on docs/getting-started-guides/ubuntu/storage.md
> +这个页面阐述了如何在 Kubernetes 集群上安装和配置持久化存储。
这个页面 --> 本页面

2017-12-06 09:35 UTC, linyouchong commented on docs/getting-started-guides/ubuntu/storage.md
> +使用 Juju 列出您云上的存储池：
列出您云上对 Juju 可用的存储池？

2017-12-06 09:35 UTC, linyouchong commented on docs/getting-started-guides/ubuntu/storage.md
> +要消耗这些持久卷，您的 pod 需要一个相关的持久卷声明，超出了本篇 README 的范围。有关更多信息，请参阅 [持久卷](/docs/concepts/storage/persistent-volumes/)文档。
消耗 --> 使用

2017-12-10 05:52 UTC, markthink reviewed
虽然总体没有什么问题，我的建议还是希望类似：{% capture overview %} 这样代码段的标签尽可能不要注释掉，仅限原始英文注释即可，这样不易在剔除英文时出现编译错误。

2017-12-10 05:52 UTC, merged