tasks-job-parallel-processing-expansion-pr-20171209
kubernetes/kubernetes-docs-zh pull request #92
Opened 2017-12-09 08:28 UTC by rootsongjc

Parallel processing job expansion Chinese translation

2017-12-09 09:34 UTC, xiaosuiba requested changes
请参考并酌情修改。
PS：译文中原文和库上有部分不同，请确认远端和本地谁需要更新，若本地未更新，请更新后重新翻译。

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +title: 使用扩展并行处理
请用注释保存原标题

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +在本示例中，我们将使用同一个模板创建多个 Kubernetes job。这可能需要您先熟悉下如何使用非并行的普通的 [Job](/docs/concepts/jobs/run-to-completion-finite-workloads/)。
普通的非并行 Job
or
普通的，非并行的 Job

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +这与 *pod 的模板* 不同， job 的模板不是 Kubernetes API 类型。它只是对 Job 对象的 yaml 表示，这里面有很多占位符，必须填充后才能使用。`$ITEM` 语法对于 Kubernetes 来说没有意义。
这与 *pod 的模板* 不同 -> 与 *pod 模板* 不同
job 的模板 -> *job 模板*
对 Job 对象的 yaml 表示 -> Job 对象的 yaml 表示。

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +在这个例子中，容器只做了一件事，就是 `echo` 一个字符串然后休眠一会。在实际使用场景下，容器通常是处理一些实质的计算，例如渲染电影的画面帧，或者是处理数据库中的一系列行。“$ITEM”参数将指定为，例如帧号或行范围。
一会 -> 一会儿/一段时间
这里的 substantial computation 指实际计算还是大量计算？
计算 -> 计算过程
“$ITEM” 中文引号
（此时）将会为帧号或行范围指定 "$ITEM" 参数。

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +该 Job 和其 Pod 的模板具有一个标签：`jobgroup-jobexample`。这个标签对于系统系统没有什么特别之处。使用标签可以很方便地一次性操作一组中的所有 Job。我们还在 pod 模板上放置了相同的标签，以便我们可以使用单个命令检查这些 Job 的所有 Pod。Job 创建好了之后，系统将添加更多的标签，将一个作业的 Pod 与另一个作业的 Pod 区分开来。请注意，`jobg
一个标签 -> 标签（纯语法建议不翻译 a）
系统系统 -> 系统

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +当前还没有办法使用直接使用一条命令一次性查看所有的 job 的输出，但是循环查看所有的 pod 的输出还是十分简单的：
使用直接使用 -> 直接使用

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +我们利用了多个 yaml 文档可以使用 `---` 分隔符连接的事实（倒数第二行）。我们可以其输出到 kubectl 来创建对象。
连接的事实 -> 意译为：连接的特性
可以其输出 -> 可以将其管道输出

2017-12-09 09:34 UTC, xiaosuiba commented on docs/tasks/job/parallel-processing-expansion.md
> +- 您需要一种方法来轻松缩放同时运行的 pod 数量。一个原因是为了避免使用太多的计算资源。另一种方法是限制对作业中所有 pod 使用的共享资源（如数据库）的并发请求数。
另一种方法 -> 为了和前文 One reason 对应，翻译为：另一个原因

2017-12-09 11:18 UTC, rootsongjc commented on docs/tasks/job/parallel-processing-expansion.md
> +在这个例子中，容器只做了一件事，就是 `echo` 一个字符串然后休眠一会。在实际使用场景下，容器通常是处理一些实质的计算，例如渲染电影的画面帧，或者是处理数据库中的一系列行。“$ITEM”参数将指定为，例如帧号或行范围。
substantial 我觉得应该翻译成“实质吧。因为此处举的例子只是echo字符串，并不做任何计算，这段话是为了解释这个例子。

2017-12-10 04:22 UTC, xiaosuiba approved these changes
LGTM

2017-12-10 05:36 UTC, merged