concepts-workloads-pods-podpresets-pr-20171210
kubernetes/kubernetes-docs-zh pull request #94
Opened 2017-12-10 14:49 UTC by rootsongjc

Pod Preset object Chinese translations

2017-12-10 15:26 UTC, markthink commented on docs/concepts/workloads/pods/podpreset.md
> +Kubernetes提供了一个准入控制器（`PodPreset`），当其启用时，Pod Preset 将会应用到传入到该控制器上的创建请求。当有 Pod 创建请求发生时，系统将执行以下操作：
建议将 `当其启用时，Pod Preset 将会应用到传入到该控制器上的创建请求` 换成这样 `当其启用时，Pod Preset 将应用创建请求传入到该控制器上` 更通顺一些。

2017-12-11 00:54 UTC, pigletfly requested changes

2017-12-11 00:54 UTC, pigletfly commented on docs/concepts/workloads/pods/podpreset.md
> +本页是关于 PodPreset 的概述，该对象用来在 Pod 创建的时候向 Pod 中注入某些信息。该信息可以包括 secret、volume、volume mount 和环境变量。
某些特定信息？

2017-12-11 00:54 UTC, pigletfly commented on docs/concepts/workloads/pods/podpreset.md
> +Kubernetes提供了一个准入控制器（`PodPreset`），当其启用时，Pod Preset 将会应用到传入到该控制器上的创建请求。当有 Pod 创建请求发生时，系统将执行以下操作：
Kubernetes 后面空格

2017-12-11 00:54 UTC, pigletfly commented on docs/concepts/workloads/pods/podpreset.md
> +2. 检查是否有 PodPreset 的标签选择器上的标签与正在创建的 pod上的标签匹配。
pod 后面空格

2017-12-11 02:33 UTC, rootsongjc commented
以上评论的地方都已经修改过了。

2017-12-11 13:45 UTC, lichuqiang commented on docs/concepts/workloads/pods/podpreset.md
> +使用 Pod Preset 可以运行 pod 模板的作者可以不必为每个 Pod 明确提供所有信息。这样一来，pod 模板的作者就不需要知道关于该服务的所有细节。
不通顺，“可以运行”-->"使得"

2017-12-11 13:45 UTC, lichuqiang commented on docs/concepts/workloads/pods/podpreset.md
> +A `Pod Preset` is an API resource for injecting additional runtime requirements into a Pod at creation time.
最好不要改动原文的格式，下同

2017-12-11 13:45 UTC, lichuqiang commented on docs/concepts/workloads/pods/podpreset.md
> +2. 检查是否有 PodPreset 的标签选择器上的标签与正在创建的 Pod 上的标签匹配。
最好断下句

2017-12-11 13:45 UTC, lichuqiang commented on docs/concepts/workloads/pods/podpreset.md
> +可能在某些情况下，您希望 Pod 不会被任何 Pod Preset 突变所改变。在这些情况下，您可以在 Pod 的 Pod Spec 中添加注释：`podpreset.admission.kubernetes.io/exclude："true"`。
这里 “mutations” 翻译成突变不太合适

2017-12-12 02:48 UTC, rootsongjc commented on docs/concepts/workloads/pods/podpreset.md
> +A `Pod Preset` is an API resource for injecting additional runtime requirements into a Pod at creation time.
我删除了原文中的换行，不换行的话实在太难看了。

2017-12-12 09:35 UTC, tianshapjq reviewed
仅供参考

2017-12-12 09:35 UTC, tianshapjq commented on docs/concepts/workloads/pods/podpreset.md
> +Kubernetes 提供了一个准入控制器（`PodPreset`），当其启用时，Pod Preset 会将应用创建请求传入到该控制器上。当有 Pod 创建请求发生时，系统将执行以下操作：
applies Pod Presets to incoming pod creation requests，应该是 “控制器会把 Pod Preset 应用到 pod 的创建请求中” 吧？也就是控制器会根据 Pod Preset 改变 pod 的创建请求内容。

2017-12-12 10:10 UTC, rootsongjc commented on docs/concepts/workloads/pods/podpreset.md
> +Kubernetes 提供了一个准入控制器（`PodPreset`），当其启用时，Pod Preset 会将应用创建请求传入到该控制器上。当有 Pod 创建请求发生时，系统将执行以下操作：
说的对，我已经修改了。

2017-12-13 07:51 UTC, merged